**Problem:**

You are given the following dataset:
1. **Audible Data** : https://1drv.ms/u/s!AiqdXCxPTydhoog8ckLN-6Cw55fzIg?e=EWgZ5d

Your task is to:
- Find the problems with the datasets.
- Define the Data Quality Dimensions.
- Try to clean the datasets.

In [80]:
import pandas as pd
import numpy as np

In [81]:
df = pd.read_csv(r"D:\Study\Data Science\Level 1\Data Analysis\Data Analysis Datasets\audible.csv")

In [82]:
df

,name,author,narrator,time,releasedate,language,stars,price,ratings
0,Geronimo Stilton #11 & #12,GeronimoStilton,BillLobely,140,2008-04-08,English,5.0,468.0,34.0
1,The Burning Maze,RickRiordan,RobbieDaymond,788,2018-01-05,English,4.5,820.0,41.0
2,The Deep End,JeffKinney,DanRussell,123,2020-06-11,English,4.5,410.0,38.0
3,Daughter of the Deep,RickRiordan,SoneelaNankani,676,2021-05-10,English,4.5,615.0,12.0
4,"The Lightning Thief: Percy Jackson, Book 1",RickRiordan,JesseBernstein,600,2010-01-13,English,4.5,820.0,181.0
...,...,...,...,...,...,...,...,...,...
87484,Last Days of the Bus Club,ChrisStewart,ChrisStewart,454,2017-09-03,English,0.0,596.0,0.0
87485,The Alps,StephenO'Shea,RobertFass,607,2017-02-21,English,0.0,820.0,0.0
87486,The Innocents Abroad,MarkTwain,FloGibson,1144,2016-12-30,English,0.0,938.0,0.0
87487,A Sentimental Journey,LaurenceSterne,AntonLesser,248,2011-02-23,English,0.0,680.0,0.0
87488,Havana,MarkKurlansky,FleetCooper,361,2017-07-03,English,0.0,569.0,0.0

## Summary about Data:(step - 1)

Basic Information:

- Dataset name: Audible Audiobooks dataset
- Number of rows: 87,489
- Number of columns: 9
- Type: Audiobook metadata dataset (information about audiobooks)
- This dataset contains details about audiobooks available on Audible, including their author, narrator, price, ratings, language, and release date.

## Info about each column(step - 2)

- name – Title of the audiobook; text column used to identify each audiobook.
- author – Name of the person who wrote the original book; text column used to analyze authors and their works.
- narrator – Person who reads or performs the audiobook recording; text column representing the voice actor of the audiobook.
- time – Duration or total length of the audiobook (usually in hours and minutes); text column describing how long the audiobook runs.
- releasedate – Date when the audiobook was released on the platform; date/text column useful for time-based analysis.
- language – Language in which the audiobook is available; categorical text column indicating audiobook language.
- stars – Average rating given by users (generally out of 5 stars); text column representing user satisfaction level.
- price – Cost of the audiobook; numeric column indicating how much the audiobook costs (some may be free).
- ratings – Total number of user ratings received by the audiobook; numeric column used to measure popularity or engagement.

## Additional Info(step - 3)
- Duplicate book titles may exist – The same audiobook can appear multiple times due to different narrators, editions, or languages.
- Highly diverse authors and narrators – The dataset includes tens of thousands of unique authors and narrators, showing a very large variety of creators.
- Uneven rating distribution – A small number of audiobooks have very high numbers of ratings, while many have very few or zero ratings.
- Data requires preprocessing – Several columns contain unstructured or mixed text formats, which must be cleaned before performing analysis.
- Real-world marketplace data – The dataset represents actual audiobook listings, so it may contain inconsistencies, duplicates, and incomplete entries typical of real-world datasets.

## Accesment (step - 4)

In [83]:
# manual acessment

In [84]:
# df.to_excel('audio.xlsx')

## Acessing

**Data Issues**
- wrong datatypes of column like releasedate , price,ratings. `validity`
- duplicated detected with labels.`accurcay` 
- 83 % ratings and stars have o values. `consistency`<br>
**Structure Issues**
- author and narrator names are clustered into each other.

In [85]:
# programatic

In [86]:
df.isnull().sum()

name           0
author         0
narrator       0
time           0
releasedate    0
language       0
stars          0
price          0
ratings        0
dtype: int64

In [87]:
df[df.duplicated(subset = ['name','author','narrator','releasedate','language'])].head(50)

,name,author,narrator,time,releasedate,language,stars,price,ratings
18,Merlin Mission Collection,MaryPopeOsborne,MaryPopeOsborne,618,2017-02-05,English,5.0,1256.0,11.0
54,Merlin Mission Collection,MaryPopeOsborne,MaryPopeOsborne,804,2017-02-05,English,5.0,1256.0,8.0
4321,My First French Lessons,AlexaPolidoro,AlexaPolidoro,59,2006-11-28,English,0.0,190.0,0.0
4322,My First French Lessons,AlexaPolidoro,AlexaPolidoro,60,2006-11-28,English,0.0,190.0,0.0
4337,My First French Lessons,AlexaPolidoro,AlexaPolidoro,51,2006-11-28,English,0.0,190.0,0.0
4652,In der Kinderstube,HansChristianAndersen,KarlheinzGabor,8,2022-04-01,german,0.0,32.0,0.0
4666,Die Lichte,HansChristianAndersen,KarlheinzGabor,11,2022-04-01,german,0.0,32.0,0.0
4670,Hotaru,KarlAlbrechtHeise,KarlheinzGabor,13,2022-04-01,german,0.0,32.0,0.0
4683,Die kleinen Grünen,HansChristianAndersen,KarlheinzGabor,10,2022-04-01,german,0.0,32.0,0.0
4708,Was man erfinden kann,HansChristianAndersen,KarlheinzGabor,10,2022-04-01,german,0.0,32.0,0.0
4711,Der schlaue Polizist,KarlAlbrechtHeise,KarlheinzGabor,7,2022-04-01,german,0.0,32.0,0.0
4716,Der weiße Fuchs,KarlAlbrechtHeise,KarlheinzGabor,6,2022-04-01,german,0.0,32.0,0.0
4722,Maorigashima,KarlAlbrechtHeise,KarlheinzGabor,6,2022-04-01,german,0.0,32.0,0.0
4724,Was die ganze Familie sagte,HansChristianAndersen,KarlheinzGabor,7,2022-04-01,german,0.0,32.0,0.0
4729,Sonnenscheingeschichten,HansChristianAndersen,KarlheinzGabor,7,2022-04-01,german,0.0,32.0,0.0
4733,Neid bringt Leid,KarlAlbrechtHeise,KarlheinzGabor,8,2022-04-01,german,0.0,32.0,0.0
4738,Wenn man mit Kobolden tanzt!,KarlAlbrechtHeise,KarlheinzGabor,5,2022-04-01,german,0.0,32.0,0.0
6205,Manolito Four-Eyes,ElviraLindo,LuciChristianBell,156,2013-03-22,English,0.0,233.0,0.0
6239,Manolito Four-Eyes,ElviraLindo,LuciChristianBell,174,2013-03-22,English,0.0,233.0,0.0
8520,A to Z Mysteries,RonRoy,DavidPittu,55,2008-12-02,English,0.0,402.0,0.0
8534,A to Z Mysteries,RonRoy,DavidPittu,47,2008-12-02,English,1.0,402.0,1.0
8553,A to Z Mysteries,RonRoy,DavidPittu,45,2008-12-02,English,5.0,402.0,1.0
9868,Das Gift des Oktopus,AiméeCarter,PeterKaempfe,430,2021-07-08,german,0.0,501.0,0.0
12599,Разговорный английский с English Spot,КристинаБьорн,ЕкатеринаКабашёва,81,2022-07-02,russian,0.0,99.0,0.0
12609,French for Beginners,AlexaPolidoro,AlexaPolidoro,308,2008-01-22,English,0.0,379.0,0.0
13388,French for Beginners,AlexaPolidoro,AlexaPolidoro,368,2008-01-22,English,0.0,379.0,0.0
13441,French for Intermediate Learners,AlexaPolidoro,AlexaPolidoro,74,2008-08-26,English,0.0,59.0,0.0
17700,Keyboard Conversations,JeffreySiegel,JeffreySiegel,55,2006-06-29,English,0.0,376.0,0.0
17751,Keyboard Conversations,JeffreySiegel,JeffreySiegel,65,2006-06-29,English,0.0,376.0,0.0
19983,Ich bin dann mal still,HorstLichter,HorstLichter,343,2021-03-05,german,0.0,602.0,0.0
20522,Master of the Senate,RobertA.Caro,GroverGardner,1119,2005-01-08,English,5.0,1088.0,2.0
20569,Master of the Senate,RobertA.Caro,GroverGardner,1295,2005-01-08,English,5.0,1088.0,2.0
24372,"Lives of the Saints: Life of Saint Dimitry, Me...",St.DmitryRostovsky,VadimMaksimov,130,2014-11-06,russian,0.0,234.0,0.0
24490,Der Mensch Martin Luther: Die Biographie,LyndalRoper,StefanWilkening,1154,2017-06-19,german,0.0,1005.0,0.0
26848,The Woman They Could Not Silence,KateMoore,KateMoore,876,2021-06-22,English,4.5,1171.0,2.0
30433,Ecological Intelligence,DanielGoleman,DanielGoleman,472,2009-04-14,English,0.0,134.0,0.0
31871,Endlich ohne Alkohol!,AllenCarr,BertCöll,506,2014-04-18,german,0.0,334.0,0.0
32318,Women's Health,HealthiNation,PatMurphyStark,58,2009-01-15,English,0.0,99.0,0.0
32426,Healthy Aging,AndrewWeil,AndrewWeil,511,2005-10-21,English,0.0,1130.0,0.0
32454,Der Lack ist ab,KaiWiesinger,"KaiWiesinger,BettinaZimmermann",208,2019-08-28,german,0.0,468.0,0.0
33371,Meditation for Extremely Busy People,BrahmaKumaris,"SisterJayanti,MikeGeorge",64,2013-12-03,English,5.0,190.0,1.0
33427,Heilen mit den Händen,"KarstenRichter,NatalyBleuel",TonioArango,497,2021-03-24,german,0.0,703.0,0.0
33495,Meditation for Extremely Busy People,BrahmaKumaris,"SisterJayanti,MikeGeorge",61,2013-12-03,English,0.0,190.0,0.0
33922,What I Talk About When I Talk About Running,HarukiMurakami,RayPorter,263,2016-07-07,English,4.5,398.0,194.0
35065,Die Heilung der Welt,RonaldD.Gerste,GertHeidenreich,541,2021-02-19,german,0.0,568.0,0.0
35123,Wie uns die Pille verändert,SarahE.Hill,TessaMittelstaedt,592,2020-11-05,german,0.0,736.0,0.0
35965,Finding Flow,MihalyCsikszentmihalyi,SeanPratt,306,2015-07-12,English,4.5,656.0,31.0
36606,Konzentriert lernen mit ADHS,SaraDörwald,HannahDautzenberg,224,2021-12-29,german,0.0,99.0,0.0
38021,When Women Ruled the World,KaraCooney,KaraCooney,555,2018-11-30,English,4.5,836.0,14.0
39603,London,PeterAckroyd,SimonCallow,180,2005-02-11,English,0.0,410.0,0.0

In [88]:
df[df.duplicated(subset = ['name','author'])]

,name,author,narrator,time,releasedate,language,stars,price,ratings
18,Merlin Mission Collection,MaryPopeOsborne,MaryPopeOsborne,618,2017-02-05,English,5.0,1256.0,11.0
46,"The Lightning Thief: Percy Jackson, Book 1",RickRiordan,WalterLewis,231,2010-01-13,English,4.0,615.0,4.0
54,Merlin Mission Collection,MaryPopeOsborne,MaryPopeOsborne,804,2017-02-05,English,5.0,1256.0,8.0
509,Los Pitufos - Historias de Pitufos,"Peyo,RaquelLuqueBenitez-traductor",GuillermoMontoya,146,2022-01-17,spanish,0.0,153.0,0.0
510,Los Pitufos - Historias de 3 minutos,"Peyo,RaquelLuqueBenitez-traductor",GuillermoMontoya,34,2022-01-17,spanish,0.0,38.0,0.0
...,...,...,...,...,...,...,...,...,...
87239,Tee and Tour,"Tee,Tour",SuzanneToren,126,2004-08-07,English,0.0,585.0,0.0
87258,Tee and Tour,"Tee,Tour",KevinYoung,109,2004-06-30,English,0.0,585.0,0.0
87347,The Great Psychedelic Armadillo Picnic,KinkyFriedman,KinkyFriedman,134,2004-08-10,English,0.0,500.0,0.0
87443,Travels with a Donkey in the Cevennes,RobertLouisStevenson,DenisLawson,171,2008-05-13,English,0.0,569.0,0.0
87486,The Innocents Abroad,MarkTwain,FloGibson,1144,2016-12-30,English,0.0,938.0,0.0

In [89]:
df

,name,author,narrator,time,releasedate,language,stars,price,ratings
0,Geronimo Stilton #11 & #12,GeronimoStilton,BillLobely,140,2008-04-08,English,5.0,468.0,34.0
1,The Burning Maze,RickRiordan,RobbieDaymond,788,2018-01-05,English,4.5,820.0,41.0
2,The Deep End,JeffKinney,DanRussell,123,2020-06-11,English,4.5,410.0,38.0
3,Daughter of the Deep,RickRiordan,SoneelaNankani,676,2021-05-10,English,4.5,615.0,12.0
4,"The Lightning Thief: Percy Jackson, Book 1",RickRiordan,JesseBernstein,600,2010-01-13,English,4.5,820.0,181.0
...,...,...,...,...,...,...,...,...,...
87484,Last Days of the Bus Club,ChrisStewart,ChrisStewart,454,2017-09-03,English,0.0,596.0,0.0
87485,The Alps,StephenO'Shea,RobertFass,607,2017-02-21,English,0.0,820.0,0.0
87486,The Innocents Abroad,MarkTwain,FloGibson,1144,2016-12-30,English,0.0,938.0,0.0
87487,A Sentimental Journey,LaurenceSterne,AntonLesser,248,2011-02-23,English,0.0,680.0,0.0
87488,Havana,MarkKurlansky,FleetCooper,361,2017-07-03,English,0.0,569.0,0.0

In [90]:
df['name']

0                        Geronimo Stilton #11 & #12
1                                  The Burning Maze
2                                      The Deep End
3                              Daughter of the Deep
4        The Lightning Thief: Percy Jackson, Book 1
                            ...
87484                     Last Days of the Bus Club
87485                                      The Alps
87486                          The Innocents Abroad
87487                         A Sentimental Journey
87488                                        Havana
Name: name, Length: 87489, dtype: object

In [91]:
# sort dataframe so similar audiobooks come together
new_df = df.sort_values(['name',"author","narrator","releasedate","language","time"])

In [92]:
new_df["time_diff"] = new_df.groupby(
    ['name',"author","narrator","releasedate","language"]
)["time"].diff().abs()

In [93]:
new_df

,name,author,narrator,time,releasedate,language,stars,price,ratings,time_diff
27841,!Aycons Management Snippets,UlviI.Aydin,UlviI.Aydin,85,2022-01-02,german,0.0,300.0,0.0,NaN
63997,"""... gegen die Verhexung des Verstandes""",ThomasSchärtl,"IngoPfeiffer,StephanLadnar,OskarVogel,",154,2021-11-24,german,0.0,233.0,0.0,NaN
20343,"""... und nie kann ich vergessen""","TimPröse,Hans-ErdmannSchönbeck",GordonPiedesack,345,2022-10-03,german,0.0,468.0,0.0,NaN
37328,"""All the Real Indians Died Off""","RoxanneDunbar-Ortiz,DinaGilio-Whitaker",LauralMerlington,354,2017-06-06,English,0.0,668.0,0.0,NaN
54127,"""Auringonsäteiden laulu""",EinoLeino,Ritva-LiisaElivuo,30,2019-03-09,finnish,0.0,32.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...
64678,ＭＡＲＣＨ大解剖(週刊東洋経済ｅビジネス新書Ｎo.339),週刊東洋経済編集部,田丸裕臣,133,2021-12-15,japanese,0.0,229.0,0.0,NaN
28363,ＮＥＯ ＨＵＭＡＮ ネオ・ヒューマン,ピーター・スコット－モーガン藤田美菜子,東城光志,913,2022-03-18,japanese,0.0,1116.0,0.0,NaN
64692,ＮＦＴの教科書 ビジネス・ブロックチェーン・法律・会計まで デジタルデータが資産になる未来,"天羽健介,増田雅史",藤井剛,659,2022-04-02,japanese,0.0,976.0,0.0,NaN
28529,ＹｏｕＴｕｂｅの極意(週刊東洋経済ｅビジネス新書Ｎo.364),週刊東洋経済編集部,岩見聖次,105,2021-12-29,japanese,0.0,204.0,0.0,NaN
29347,ｔｈｅ ｆｏｕｒ ＧＡＦＡ 四騎士が創り変えた世界,"スコット・ギャロウェイ,渡会圭子",あんべあつし,675,2021-04-16,japanese,0.0,976.0,0.0,NaN

In [94]:
new_df["duplicate_label"] = new_df["time_diff"].apply(
    lambda x: "duplicate" if pd.notna(x) and x < 5 else "non_duplicate"
)

In [95]:
new_df[new_df['duplicate_label'] =='duplicate']

,name,author,narrator,time,releasedate,language,stars,price,ratings,time_diff,duplicate_label
64722,100 quotes by Benjamin Franklin,BenjaminFranklin,PaulSpera,19,2018-07-03,English,5.0,200.0,2.0,0.0,duplicate
8534,A to Z Mysteries,RonRoy,DavidPittu,47,2008-12-02,English,1.0,402.0,1.0,2.0,duplicate
8490,A to Z Mysteries,RonRoy,DavidPittu,48,2008-12-02,English,4.5,402.0,3.0,1.0,duplicate
62272,Atomic Habits,JamesClear,JamesClear,335,2018-10-18,English,5.0,820.0,12573.0,0.0,duplicate
41111,Aurangzeb: The Man and the Myth,AudreyTrushcke,DilshadKhurana,230,2020-03-24,English,4.0,1005.0,58.0,0.0,duplicate
...,...,...,...,...,...,...,...,...,...,...,...
38021,When Women Ruled the World,KaraCooney,KaraCooney,555,2018-11-30,English,4.5,836.0,14.0,0.0,duplicate
64428,Wings of Fire,"APJAbdulKalam,ArunTiwari",GirishKarnad,75,2020-01-04,English,5.0,75.0,1827.0,0.0,duplicate
68902,ダイエット瞑想,志麻絹依,志麻絹依,20,2015-01-09,japanese,0.0,2399.0,0.0,3.0,duplicate
68810,ダイエット瞑想,志麻絹依,志麻絹依,23,2015-01-09,japanese,0.0,781.0,0.0,3.0,duplicate
55500,芋虫,江戸川乱歩,鬼城院護,54,2022-03-31,japanese,0.0,251.0,0.0,1.0,duplicate

=== UNIVERSAL EDA ANOMALY DETECTION CHECKLIST ===

--- PHASE 1: STRUCTURAL CHECKS ---

S1. Shape & Schema Inspection
    df.shape
    df.dtypes
    df.info()

S2. Missing Value Audit
    df.isnull().sum()
    df.isnull().mean()

S3. Duplicate Detection
    df.duplicated().sum()
    df.duplicated(subset=['col']).sum()


--- PHASE 2: DISTRIBUTION ANALYSIS ---

D1. Descriptive Statistics
    df.describe()
    df['col'].mean()
    df['col'].median()

D2. Value Counts (for categoricals)
    df['col'].value_counts()
    df['col'].nunique()

D3. Min / Max Boundary Check
    df['col'].min()
    df['col'].max()
    df.nlargest(10, 'col')
    df.nsmallest(10, 'col')


--- PHASE 3: STATISTICAL OUTLIER DETECTION ---

N1. IQR Method (works on any distribution)
    Q1 = df['col'].quantile(0.25)
    Q3 = df['col'].quantile(0.75)
    IQR = Q3 - Q1
    outliers = df[(df['col'] < Q1 - 1.5*IQR) | (df['col'] > Q3 + 1.5*IQR)]

N2. Z-Score Method (for normal distributions)
    from scipy import stats
    z = (df['col'] - df['col'].mean()) / df['col'].std()
    outliers = df[z.abs() > 3]

N3. Percentile Thresholds
    df[df['col'] > df['col'].quantile(0.99)]
    df[df['col'] < df['col'].quantile(0.01)]


--- PHASE 4: LOGIC / SEMANTIC RULES ---

L1. Cross-Column Consistency Check
    df[(df['col1'] == 0) & (df['col2'] > 0)]
    df[(df['price'] == 0) & (df['ratings'] > 0)]

L2. Group-By Variance Check
    df.groupby('name')['price'].agg(['min', 'max', 'count'])
    # flag where min != max

L3. String Pattern / Format Check
    df['col'].str.contains(' ')
    df['col'].str.match(r'^[A-Z]')
    df['col'].str.len().value_counts()

L4. Date Boundary Check
    df['date'] = pd.to_datetime(df['date'], errors='coerce')
    df[df['date'] > pd.Timestamp.today()]   # future dates
    df[df['date'].isnull()]                 # invalid dates
    df['date'].dt.year.value_counts()       # year distribution


=== QUICK REFERENCE ORDER ===
1.  df.shape / df.dtypes / df.info()
2.  df.isnull().sum()
3.  df.duplicated().sum()
4.  df.describe()
5.  df['col'].value_counts()
6.  df['col'].min() / df['col'].max()
7.  IQR outlier filter
8.  Z-score filter
9.  Percentile thresholds
10. Cross-column logic checks
11. Group-by variance check
12. String pattern check
13. Date boundary check

In [96]:
# checking for other anmolies

In [97]:
df.describe()

               time         stars         price       ratings
count  87489.000000  87489.000000  87489.000000  87489.000000
mean     417.497663      0.767811    559.009246      3.723371
std      364.559399      1.709640    336.096642     86.499601
min        1.000000      0.000000      0.000000      0.000000
25%      142.000000      0.000000    268.000000      0.000000
50%      386.000000      0.000000    585.000000      0.000000
75%      584.000000      0.000000    755.000000      0.000000
max     8595.000000      5.000000   7198.000000  12573.000000

In [98]:
df[df['time'] == 8595]

,name,author,narrator,time,releasedate,language,stars,price,ratings
51330,All DEAD,T.W.Brown,AndrewMcFerrin,8595,2019-09-27,English,4.0,1003.0,1.0

In [99]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87489 entries, 0 to 87488
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         87489 non-null  object
 1   author       87489 non-null  object
 2   narrator     87489 non-null  object
 3   time         87489 non-null  int64
 4   releasedate  87489 non-null  object
 5   language     87489 non-null  object
 6   stars        87489 non-null  float64
 7   price        87489 non-null  float64
 8   ratings      87489 non-null  float64
dtypes: float64(3), int64(1), object(5)
memory usage: 6.0+ MB

In [100]:
df[df['time'] == 1]

,name,author,narrator,time,releasedate,language,stars,price,ratings
1203,Food,DanielNunn,anonymous,1,2022-03-16,English,0.0,82.0,0.0
1210,Rainbow Sambhar,"AntraKhurana,MathangiSubramanian",ShaheenKhan,1,2021-12-23,English,0.0,32.0,0.0
1222,All About Snowmen,KathrynClay,anonymous,1,2022-08-03,English,0.0,82.0,0.0
1242,Birthday Cakes,SarahL.Schuette,anonymous,1,2022-02-25,English,0.0,82.0,0.0
1249,Birthday Party Games,SarahL.Schuette,Anonymous,1,2022-02-21,English,0.0,82.0,0.0
...,...,...,...,...,...,...,...,...,...
87171,第二十五話サン・ミシェルのいいカフェ：ぼくの旅の手帖〜または珈琲のある風景,森本哲郎,小野田英一,1,2015-11-20,japanese,0.0,139.0,0.0
87175,第九話オラン最後の夕べ：ぼくの旅の手帖〜または珈琲のある風景,森本哲郎,小野田英一,1,2015-11-19,japanese,0.0,139.0,0.0
87176,第一話リューベックの追憶:ぼくの旅の手帖〜または珈琲のある風景,森本哲郎,小野田英一,1,2015-07-23,japanese,0.0,139.0,0.0
87180,第七話バグダードの茶屋:ぼくの旅の手帖〜または珈琲のある風景,森本哲郎,小野田英一,1,2015-07-13,japanese,0.0,139.0,0.0
87192,第十八話バンコックの憂鬱：ぼくの旅の手帖〜または珈琲のある風景,森本哲郎,小野田英一,1,2015-11-19,japanese,0.0,139.0,0.0

In [121]:
## Acessing

# **Data Issues**
# - wrong datatypes of column like releasedate , price,ratings. `validity`
# - duplicated detected with labels.`accurcay` 
# - 83 % ratings and stars have o values. `consistency`<br>
# **Structure Issues**
# - author and narrator names are clustered into each other.

## Cleaning

In [110]:
df

,name,author,narrator,time,releasedate,language,stars,price,ratings
0,Geronimo Stilton #11 & #12,GeronimoStilton,BillLobely,140,2008-04-08,English,5.0,468.0,34.0
1,The Burning Maze,RickRiordan,RobbieDaymond,788,2018-01-05,English,4.5,820.0,41.0
2,The Deep End,JeffKinney,DanRussell,123,2020-06-11,English,4.5,410.0,38.0
3,Daughter of the Deep,RickRiordan,SoneelaNankani,676,2021-05-10,English,4.5,615.0,12.0
4,"The Lightning Thief: Percy Jackson, Book 1",RickRiordan,JesseBernstein,600,2010-01-13,English,4.5,820.0,181.0
...,...,...,...,...,...,...,...,...,...
87484,Last Days of the Bus Club,ChrisStewart,ChrisStewart,454,2017-09-03,English,0.0,596.0,0.0
87485,The Alps,StephenO'Shea,RobertFass,607,2017-02-21,English,0.0,820.0,0.0
87486,The Innocents Abroad,MarkTwain,FloGibson,1144,2016-12-30,English,0.0,938.0,0.0
87487,A Sentimental Journey,LaurenceSterne,AntonLesser,248,2011-02-23,English,0.0,680.0,0.0
87488,Havana,MarkKurlansky,FleetCooper,361,2017-07-03,English,0.0,569.0,0.0

In [107]:
df.dtypes

name            object
author          object
narrator        object
time             int64
releasedate     object
language        object
stars          float64
price          float64
ratings        float64
dtype: object

In [109]:
df['time'].astype('datetime64[m]')

0       1970-01-01 02:20:00
1       1970-01-01 13:08:00
2       1970-01-01 02:03:00
3       1970-01-01 11:16:00
4       1970-01-01 10:00:00
                ...
87484   1970-01-01 07:34:00
87485   1970-01-01 10:07:00
87486   1970-01-01 19:04:00
87487   1970-01-01 04:08:00
87488   1970-01-01 06:01:00
Name: time, Length: 87489, dtype: datetime64[s]

In [114]:
df['time'] = pd.to_timedelta(df['time'], unit='m')

In [116]:
df['price'] = df['price'].astype('int')

In [120]:
df['ratings'] = df['ratings'].astype('int')

## Handling Tidyness

In [ ]:
df['author'].split()

0        GeronimoStilton
1            RickRiordan
2             JeffKinney
3            RickRiordan
4            RickRiordan
              ...
87484       ChrisStewart
87485      StephenO'Shea
87486          MarkTwain
87487     LaurenceSterne
87488      MarkKurlansky
Name: author, Length: 87489, dtype: object

In [125]:
import re

def fix_name(text):
    text = str(text)
    text = re.sub(r'([a-z])([A-Z])', r'\1 \2', text)       # camelCase split
    text = re.sub(r'([A-Z]+)([A-Z][a-z])', r'\1 \2', text) # acronym split
    return text.strip()

df['author_clean']   = df['author'].apply(fix_name)
df['narrator_clean'] = df['narrator'].apply(fix_name)

In [126]:
df

,name,author,narrator,time,releasedate,language,stars,price,ratings,author_clean,narrator_clean
0,Geronimo Stilton #11 & #12,GeronimoStilton,BillLobely,0 days 02:20:00,2008-04-08,English,5.0,468,34,Geronimo Stilton,Bill Lobely
1,The Burning Maze,RickRiordan,RobbieDaymond,0 days 13:08:00,2018-01-05,English,4.5,820,41,Rick Riordan,Robbie Daymond
2,The Deep End,JeffKinney,DanRussell,0 days 02:03:00,2020-06-11,English,4.5,410,38,Jeff Kinney,Dan Russell
3,Daughter of the Deep,RickRiordan,SoneelaNankani,0 days 11:16:00,2021-05-10,English,4.5,615,12,Rick Riordan,Soneela Nankani
4,"The Lightning Thief: Percy Jackson, Book 1",RickRiordan,JesseBernstein,0 days 10:00:00,2010-01-13,English,4.5,820,181,Rick Riordan,Jesse Bernstein
...,...,...,...,...,...,...,...,...,...,...,...
87484,Last Days of the Bus Club,ChrisStewart,ChrisStewart,0 days 07:34:00,2017-09-03,English,0.0,596,0,Chris Stewart,Chris Stewart
87485,The Alps,StephenO'Shea,RobertFass,0 days 10:07:00,2017-02-21,English,0.0,820,0,Stephen O'Shea,Robert Fass
87486,The Innocents Abroad,MarkTwain,FloGibson,0 days 19:04:00,2016-12-30,English,0.0,938,0,Mark Twain,Flo Gibson
87487,A Sentimental Journey,LaurenceSterne,AntonLesser,0 days 04:08:00,2011-02-23,English,0.0,680,0,Laurence Sterne,Anton Lesser
87488,Havana,MarkKurlansky,FleetCooper,0 days 06:01:00,2017-07-03,English,0.0,569,0,Mark Kurlansky,Fleet Cooper

In [128]:
df.drop(columns=['author','narrator'],inplace=True)

In [131]:
df.rename(columns={'author_clean':'author','narrator_clean':'narrator'},inplace=True)

In [132]:
df

,name,time,releasedate,language,stars,price,ratings,author,narrator
0,Geronimo Stilton #11 & #12,0 days 02:20:00,2008-04-08,English,5.0,468,34,Geronimo Stilton,Bill Lobely
1,The Burning Maze,0 days 13:08:00,2018-01-05,English,4.5,820,41,Rick Riordan,Robbie Daymond
2,The Deep End,0 days 02:03:00,2020-06-11,English,4.5,410,38,Jeff Kinney,Dan Russell
3,Daughter of the Deep,0 days 11:16:00,2021-05-10,English,4.5,615,12,Rick Riordan,Soneela Nankani
4,"The Lightning Thief: Percy Jackson, Book 1",0 days 10:00:00,2010-01-13,English,4.5,820,181,Rick Riordan,Jesse Bernstein
...,...,...,...,...,...,...,...,...,...
87484,Last Days of the Bus Club,0 days 07:34:00,2017-09-03,English,0.0,596,0,Chris Stewart,Chris Stewart
87485,The Alps,0 days 10:07:00,2017-02-21,English,0.0,820,0,Stephen O'Shea,Robert Fass
87486,The Innocents Abroad,0 days 19:04:00,2016-12-30,English,0.0,938,0,Mark Twain,Flo Gibson
87487,A Sentimental Journey,0 days 04:08:00,2011-02-23,English,0.0,680,0,Laurence Sterne,Anton Lesser
87488,Havana,0 days 06:01:00,2017-07-03,English,0.0,569,0,Mark Kurlansky,Fleet Cooper

## Handling Acuuracy

In [139]:
df = df.sort_values(['name',"author","narrator","releasedate","language","time"])