In [3]:
import numpy as np
import pandas as pd

# to visualize all the column, run the below code
pd.options.display.max_columns = None
# to show all the records, use the below code
# pd.options.display.max_rows = None

## Fifa Worldcup - 2022 dataset.

You can find the dataset from [here](https://www.kaggle.com/datasets/sayanroy729/fifa-worldcup-2022-results).

Also you can directly use an url to read the dataset by using `pd.read_csv()` method. Check the below code cell.

In [4]:
# To get the details about the dataset, please visit
# https://www.kaggle.com/datasets/sayanroy729/fifa-worldcup-2022-results

url = "https://docs.google.com/spreadsheets/d/e/2PACX-1vT3D_x_4DS6d51LKJ7ze1sxT5WpV5uiSVOFYHLwBiGru6vFyVv5h5-83AwFjxWYiWfCDjDAaarHAV-k/pub?gid=0&single=true&output=csv"
df = pd.read_csv(url)
df.head()

,Sl. No,Match No.,Team,Against,Group,Goal,Possession (%),Inside Penalty Area,Outside Penalty Area,Assists,Total Attempts,On Target,Off Target,Target in Penalty,Target from Outside,Left Channel,Left Inside Channel,Central Channel,Right Inside Channel,Right Channel,Receptions MD,Receptions D,Attempted Line Breaks,Completed Line Breaks,Attempted Defensive Line Breaks,Completed Defensive Line Breaks,Yellow Cards,Red Cards,Fouls Against,Offsides,Passes,Passes Completed,Crosses,Crosses Completed,Corners,Free Kicks,Penalties Scored,Pts
0,1,1,Qatar,Ecuador,A,0,40,0,0,0,5,0,5,2,3,15,0,3,1,9,45,5,159,100,6,4,4,0,15,3,453,387,10,5,1,19,0,0
1,2,1,Ecuador,Qatar,A,2,46,2,0,1,5,5,2,4,1,8,7,6,4,6,55,10,159,103,6,4,2,0,15,4,484,419,26,10,3,17,1,3
2,3,2,England,Iran,B,6,69,6,0,6,13,7,3,10,3,11,5,2,3,11,72,15,133,94,8,6,0,0,9,2,810,733,29,9,8,16,0,3
3,4,2,Iran,England,B,2,20,2,0,1,8,3,4,6,2,3,0,3,1,1,34,1,56,19,1,1,2,0,14,2,232,156,11,3,0,10,1,0
4,5,3,Senegal,Netherlands,A,0,39,0,0,0,15,4,7,8,7,12,4,2,4,13,101,12,143,86,6,6,2,0,13,2,391,326,22,8,6,14,0,0

### `Q-1:` Use the football dataset. Find out the total percentages that each team made on target. Display the result as a python dictionary where the keys are the team list and the values are the percentage values. Round off the percentage values up to 2 decimal places.

*Help:*
- First, find out how many total teams are participated in this worldcup. For that, you can use `unique()` method on the column "Team" or "Against".
- Loop through the teams list that you have found in previous section, and then filter the dataset according to that. After filtering the dataset, find out total attempts sum and total on target sum.
- After getting these values, find out the percentage by total on target divided by total attempts and multiply by 100. And store to a python dictionary where the key will be the team name and the values will be the percentages.
- At the end,sort the dictionary by the values (not by the keys) and print the result.


**Sample Output:**
```bash
{'Costa Rica': 54.55,
 'Cameroon': 51.85,
 'Ecuador': 48.15,
 'Argentina': 46.99,
 'Brazil': 45.56,
 'England': 45.0,
 'Portugal': 40.32,
 'Ghana': 40.0,
 'Netherlands': 39.02,
 'Korea Republic': 36.73,
 'Australia': 36.0,
 'Mexico': 34.88,
 'Croatia': 34.78,
 'Germany': 34.33,
 'France': 32.97,
 'Spain': 32.69,
 'Belgium': 32.35,
 'Serbia': 32.26,
 'Iran': 31.43,
 'Uruguay': 31.25,
 'United States': 31.11,
 'Saudi Arabia': 31.03,
 'Senegal': 30.77,
 'Denmark': 30.56,
 'Switzerland': 30.56,
 'Japan': 30.23,
 'Wales': 29.17,
 'Qatar': 28.57,
 'Morocco': 28.3,
 'Tunisia': 26.67,
 'Poland': 25.0,
 'Canada': 17.65}
```

In [ ]:
# code here

In [5]:
teams = df["Team"].unique()
print(len(teams))   # total number of teams

32

In [6]:
team_on_target_percentage = {}

for team in teams:
    team_df = df[df["Team"] == team]

    total_attempts = team_df["Total Attempts"].sum()
    total_on_target = team_df["On Target"].sum()

    if total_attempts > 0:  # safety check
        percentage = (total_on_target / total_attempts) * 100
    else:
        percentage = 0

    team_on_target_percentage[team] = round(percentage, 2)

In [7]:
sorted_team_on_target_percentage = dict(
    sorted(
        team_on_target_percentage.items(),
        key=lambda item: item[1],
        reverse=True
    )
)

In [8]:
sorted_team_on_target_percentage

{'Costa Rica': np.float64(54.55),
 'Cameroon': np.float64(51.85),
 'Ecuador': np.float64(48.15),
 'Argentina': np.float64(46.15),
 'Brazil': np.float64(45.56),
 'England': np.float64(45.0),
 'Portugal': np.float64(40.32),
 'Ghana': np.float64(40.0),
 'Netherlands': np.float64(39.02),
 'Korea Republic': np.float64(36.73),
 'Australia': np.float64(36.0),
 'Mexico': np.float64(34.88),
 'France': np.float64(34.65),
 'Germany': np.float64(34.33),
 'Croatia': np.float64(33.73),
 'Spain': np.float64(32.69),
 'Belgium': np.float64(32.35),
 'Serbia': np.float64(32.26),
 'Iran': np.float64(31.43),
 'Uruguay': np.float64(31.25),
 'United States': np.float64(31.11),
 'Saudi Arabia': np.float64(31.03),
 'Senegal': np.float64(30.77),
 'Denmark': np.float64(30.56),
 'Switzerland': np.float64(30.56),
 'Japan': np.float64(30.23),
 'Wales': np.float64(29.17),
 'Qatar': np.float64(28.57),
 'Morocco': np.float64(28.33),
 'Tunisia': np.float64(26.67),
 'Poland': np.float64(25.0),
 'Canada': np.float64(17.65)}

### `Q-2:` Find out how many times the teams are played in this Fifa Worldcup-2022. On top of this, find out the ranks of the teams.

Note: The `DataFrame.rank()` method takes an optiinal parameter named `method`. This parameter takes different values, but one of them is `average` which is by-default. So, when you do the rank, you will get some 2.5 like floating values. But if you change the value as `first`, then you will get in integers but the datatype will be float. So, try with `method="first"` parameter.

In [ ]:
# code here

In [9]:
team_match_count = df["Team"].value_counts()
team_match_count

Team
France            7
Argentina         7
Croatia           7
Morocco           7
Brazil            5
Portugal          5
England           5
Netherlands       5
Spain             4
Japan             4
Switzerland       4
Korea Republic    4
Australia         4
Poland            4
Senegal           4
United States     4
Mexico            3
Saudi Arabia      3
Denmark           3
Tunisia           3
Iran              3
Ecuador           3
Qatar             3
Wales             3
Canada            3
Belgium           3
Costa Rica        3
Germany           3
Uruguay           3
Cameroon          3
Ghana             3
Serbia            3
Name: count, dtype: int64

In [10]:
team_stats = team_match_count.reset_index()
team_stats.columns = ["Team", "Matches_Played"]
team_stats

              Team  Matches_Played
0           France               7
1        Argentina               7
2          Croatia               7
3          Morocco               7
4           Brazil               5
5         Portugal               5
6          England               5
7      Netherlands               5
8            Spain               4
9            Japan               4
10     Switzerland               4
11  Korea Republic               4
12       Australia               4
13          Poland               4
14         Senegal               4
15   United States               4
16          Mexico               3
17    Saudi Arabia               3
18         Denmark               3
19         Tunisia               3
20            Iran               3
21         Ecuador               3
22           Qatar               3
23           Wales               3
24          Canada               3
25         Belgium               3
26      Costa Rica               3
27         Germany               3
28         Uruguay               3
29        Cameroon               3
30           Ghana               3
31          Serbia               3

In [11]:
team_stats["Rank"] = team_stats["Matches_Played"].rank(method="first", ascending=False)
team_stats

              Team  Matches_Played  Rank
0           France               7   1.0
1        Argentina               7   2.0
2          Croatia               7   3.0
3          Morocco               7   4.0
4           Brazil               5   5.0
5         Portugal               5   6.0
6          England               5   7.0
7      Netherlands               5   8.0
8            Spain               4   9.0
9            Japan               4  10.0
10     Switzerland               4  11.0
11  Korea Republic               4  12.0
12       Australia               4  13.0
13          Poland               4  14.0
14         Senegal               4  15.0
15   United States               4  16.0
16          Mexico               3  17.0
17    Saudi Arabia               3  18.0
18         Denmark               3  19.0
19         Tunisia               3  20.0
20            Iran               3  21.0
21         Ecuador               3  22.0
22           Qatar               3  23.0
23           Wales               3  24.0
24          Canada               3  25.0
25         Belgium               3  26.0
26      Costa Rica               3  27.0
27         Germany               3  28.0
28         Uruguay               3  29.0
29        Cameroon               3  30.0
30           Ghana               3  31.0
31          Serbia               3  32.0

In [12]:
team_stats = team_stats.sort_values("Rank")
team_stats.reset_index(drop=True, inplace=True)
team_stats

              Team  Matches_Played  Rank
0           France               7   1.0
1        Argentina               7   2.0
2          Croatia               7   3.0
3          Morocco               7   4.0
4           Brazil               5   5.0
5         Portugal               5   6.0
6          England               5   7.0
7      Netherlands               5   8.0
8            Spain               4   9.0
9            Japan               4  10.0
10     Switzerland               4  11.0
11  Korea Republic               4  12.0
12       Australia               4  13.0
13          Poland               4  14.0
14         Senegal               4  15.0
15   United States               4  16.0
16          Mexico               3  17.0
17    Saudi Arabia               3  18.0
18         Denmark               3  19.0
19         Tunisia               3  20.0
20            Iran               3  21.0
21         Ecuador               3  22.0
22           Qatar               3  23.0
23           Wales               3  24.0
24          Canada               3  25.0
25         Belgium               3  26.0
26      Costa Rica               3  27.0
27         Germany               3  28.0
28         Uruguay               3  29.0
29        Cameroon               3  30.0
30           Ghana               3  31.0
31          Serbia               3  32.0

### `Q-3:` Find out these below topics:
- The information about the Fifa worldcup dataset.
- The description about the Fifa worldcup dataset
- Check is there any missing values, if there is any missing values, fill that value with the average value for that particular column.
- Drop all the duplicate rows permanently.
- Drop the columns: "Sl No", "Match No.", "Red Cards" and "Pts" permanently.

In [13]:
# Basic info: columns, non-null counts, datatypes
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128 entries, 0 to 127
Data columns (total 38 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Sl. No                           128 non-null    int64
 1   Match No.                        128 non-null    int64
 2   Team                             128 non-null    object
 3   Against                          128 non-null    object
 4   Group                            128 non-null    object
 5   Goal                             128 non-null    int64
 6   Possession (%)                   128 non-null    int64
 7   Inside Penalty Area              128 non-null    int64
 8   Outside Penalty Area             128 non-null    int64
 9   Assists                          128 non-null    int64
 10  Total Attempts                   128 non-null    int64
 11  On Target                        128 non-null    int64
 12  Off Target                       128 non-null    int64
 13  Target in Penalty                128 non-null    int64
 14  Target from Outside              128 non-null    int64
 15  Left Channel                     128 non-null    int64
 16  Left Inside Channel              128 non-null    int64
 17  Central Channel                  128 non-null    int64
 18  Right Inside Channel             128 non-null    int64
 19  Right Channel                    128 non-null    int64
 20  Receptions MD                    128 non-null    int64
 21  Receptions D                     128 non-null    int64
 22  Attempted Line Breaks            128 non-null    int64
 23  Completed Line Breaks            128 non-null    int64
 24  Attempted Defensive Line Breaks  128 non-null    int64
 25  Completed Defensive Line Breaks  128 non-null    int64
 26  Yellow Cards                     128 non-null    int64
 27  Red Cards                        128 non-null    int64
 28  Fouls Against                    128 non-null    int64
 29  Offsides                         128 non-null    int64
 30  Passes                           128 non-null    int64
 31  Passes Completed                 128 non-null    int64
 32  Crosses                          128 non-null    int64
 33  Crosses Completed                128 non-null    int64
 34  Corners                          128 non-null    int64
 35  Free Kicks                       128 non-null    int64
 36  Penalties Scored                 128 non-null    int64
 37  Pts                              128 non-null    int64
dtypes: int64(35), object(3)
memory usage: 38.1+ KB

In [14]:
# Description: summary statistics for numeric columns
df.describe()

,Sl. No,Match No.,Goal,Possession (%),Inside Penalty Area,Outside Penalty Area,Assists,Total Attempts,On Target,Off Target,Target in Penalty,Target from Outside,Left Channel,Left Inside Channel,Central Channel,Right Inside Channel,Right Channel,Receptions MD,Receptions D,Attempted Line Breaks,Completed Line Breaks,Attempted Defensive Line Breaks,Completed Defensive Line Breaks,Yellow Cards,Red Cards,Fouls Against,Offsides,Passes,Passes Completed,Crosses,Crosses Completed,Corners,Free Kicks,Penalties Scored,Pts
count,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000
mean,64.500000,32.500000,1.343750,43.476562,1.203125,0.117188,0.914062,11.257812,4.007812,4.835938,6.914062,4.343750,13.562500,4.671875,4.906250,4.648438,12.234375,92.703125,12.453125,169.281250,109.476562,14.812500,8.265625,1.726562,0.023438,12.320312,1.976562,502.859375,430.929688,19.523438,4.898438,4.468750,14.250000,0.335938,1.429688
std,37.094474,18.545539,1.342448,11.442403,1.324270,0.322907,1.150333,5.406683,2.588576,2.610630,3.998085,2.733397,6.901729,2.886595,3.080131,2.936573,6.176517,29.440547,18.152399,34.120661,30.776298,7.230458,5.101311,1.514834,0.151883,4.691983,1.731891,160.160487,160.893724,8.596799,3.520111,2.774852,4.712189,0.941412,1.389973
min,1.000000,1.000000,0.000000,14.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,0.000000,1.000000,32.000000,0.000000,56.000000,19.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,225.000000,156.000000,4.000000,0.000000,0.000000,5.000000,0.000000,0.000000
25%,32.750000,16.750000,0.000000,35.000000,0.000000,0.000000,0.000000,7.750000,2.000000,3.000000,4.000000,3.000000,8.000000,2.000000,3.000000,3.000000,8.000000,72.750000,7.000000,149.500000,87.750000,10.000000,5.000000,1.000000,0.000000,9.000000,1.000000,398.250000,323.250000,13.000000,3.000000,2.000000,11.000000,0.000000,0.000000
50%,64.500000,32.500000,1.000000,45.000000,1.000000,0.000000,1.000000,10.000000,4.000000,4.000000,6.000000,4.000000,12.000000,4.500000,4.000000,4.000000,11.000000,93.000000,9.000000,170.500000,106.000000,15.000000,8.000000,2.000000,0.000000,12.000000,2.000000,495.500000,419.000000,19.000000,4.000000,4.000000,14.000000,0.000000,1.000000
75%,96.250000,48.250000,2.000000,51.000000,2.000000,0.000000,1.000000,14.000000,6.000000,6.000000,9.000000,5.000000,18.000000,7.000000,6.250000,6.000000,16.250000,111.250000,14.000000,188.000000,129.000000,20.000000,11.000000,2.000000,0.000000,15.000000,3.000000,589.500000,519.750000,24.000000,6.000000,6.000000,17.000000,0.000000,3.000000
max,128.000000,64.000000,7.000000,78.000000,7.000000,1.000000,6.000000,32.000000,13.000000,17.000000,24.000000,15.000000,36.000000,13.000000,16.000000,19.000000,29.000000,186.000000,192.000000,259.000000,192.000000,40.000000,27.000000,8.000000,1.000000,30.000000,10.000000,1070.000000,994.000000,53.000000,25.000000,14.000000,30.000000,5.000000,3.000000

In [15]:
df.isnull().sum()

Sl. No                             0
Match No.                          0
Team                               0
Against                            0
Group                              0
Goal                               0
Possession (%)                     0
Inside Penalty Area                0
Outside Penalty Area               0
Assists                            0
Total Attempts                     0
On Target                          0
Off Target                         0
Target in Penalty                  0
Target from Outside                0
Left Channel                       0
Left Inside Channel                0
Central Channel                    0
Right Inside Channel               0
Right Channel                      0
Receptions MD                      0
Receptions D                       0
Attempted Line Breaks              0
Completed Line Breaks              0
Attempted Defensive Line Breaks    0
Completed Defensive Line Breaks    0
Yellow Cards                       0
Red Cards                          0
Fouls Against                      0
Offsides                           0
Passes                             0
Passes Completed                   0
Crosses                            0
Crosses Completed                  0
Corners                            0
Free Kicks                         0
Penalties Scored                   0
Pts                                0
dtype: int64

In [16]:
numeric_cols = df.select_dtypes(include=["float64", "int64"]).columns

for col in numeric_cols:
    df[col].fillna(df[col].mean(), inplace=True)

/tmp/ipython-input-90052771.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mean(), inplace=True)

In [17]:
df.drop_duplicates(inplace=True)

In [18]:
columns_to_drop = ["Sl. No", "Match No.", "Red Cards", "Pts"]
df.drop(columns=columns_to_drop, inplace=True)

In [19]:
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128 entries, 0 to 127
Data columns (total 34 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Team                             128 non-null    object
 1   Against                          128 non-null    object
 2   Group                            128 non-null    object
 3   Goal                             128 non-null    int64
 4   Possession (%)                   128 non-null    int64
 5   Inside Penalty Area              128 non-null    int64
 6   Outside Penalty Area             128 non-null    int64
 7   Assists                          128 non-null    int64
 8   Total Attempts                   128 non-null    int64
 9   On Target                        128 non-null    int64
 10  Off Target                       128 non-null    int64
 11  Target in Penalty                128 non-null    int64
 12  Target from Outside              128 non-null    int64
 13  Left Channel                     128 non-null    int64
 14  Left Inside Channel              128 non-null    int64
 15  Central Channel                  128 non-null    int64
 16  Right Inside Channel             128 non-null    int64
 17  Right Channel                    128 non-null    int64
 18  Receptions MD                    128 non-null    int64
 19  Receptions D                     128 non-null    int64
 20  Attempted Line Breaks            128 non-null    int64
 21  Completed Line Breaks            128 non-null    int64
 22  Attempted Defensive Line Breaks  128 non-null    int64
 23  Completed Defensive Line Breaks  128 non-null    int64
 24  Yellow Cards                     128 non-null    int64
 25  Fouls Against                    128 non-null    int64
 26  Offsides                         128 non-null    int64
 27  Passes                           128 non-null    int64
 28  Passes Completed                 128 non-null    int64
 29  Crosses                          128 non-null    int64
 30  Crosses Completed                128 non-null    int64
 31  Corners                          128 non-null    int64
 32  Free Kicks                       128 non-null    int64
 33  Penalties Scored                 128 non-null    int64
dtypes: int64(31), object(3)
memory usage: 34.1+ KB

,Team,Against,Group,Goal,Possession (%),Inside Penalty Area,Outside Penalty Area,Assists,Total Attempts,On Target,Off Target,Target in Penalty,Target from Outside,Left Channel,Left Inside Channel,Central Channel,Right Inside Channel,Right Channel,Receptions MD,Receptions D,Attempted Line Breaks,Completed Line Breaks,Attempted Defensive Line Breaks,Completed Defensive Line Breaks,Yellow Cards,Fouls Against,Offsides,Passes,Passes Completed,Crosses,Crosses Completed,Corners,Free Kicks,Penalties Scored
0,Qatar,Ecuador,A,0,40,0,0,0,5,0,5,2,3,15,0,3,1,9,45,5,159,100,6,4,4,15,3,453,387,10,5,1,19,0
1,Ecuador,Qatar,A,2,46,2,0,1,5,5,2,4,1,8,7,6,4,6,55,10,159,103,6,4,2,15,4,484,419,26,10,3,17,1
2,England,Iran,B,6,69,6,0,6,13,7,3,10,3,11,5,2,3,11,72,15,133,94,8,6,0,9,2,810,733,29,9,8,16,0
3,Iran,England,B,2,20,2,0,1,8,3,4,6,2,3,0,3,1,1,34,1,56,19,1,1,2,14,2,232,156,11,3,0,10,1
4,Senegal,Netherlands,A,0,39,0,0,0,15,4,7,8,7,12,4,2,4,13,101,12,143,86,6,6,2,13,2,391,326,22,8,6,14,0

In [ ]:
# code here

###`Q-4:` Do these below operations:
- Find out the rank based on the "Team" column and save the result by adding a new column named "Rank".
- Change the datatype of this column to integer by using `np.int16`
- Set the index of the DataFrame by using this "Rank" column permanently.
- After that, sort the dataframe based on the "Rank" index.

In [ ]:
# code here

In [20]:
df['Rank'] = df['Team'].rank(method='first')  # method='first' to avoid averaging

In [21]:
# Count how many matches each team played
team_counts = df['Team'].value_counts()

# Map the counts back to the DataFrame
df['Matches_Played'] = df['Team'].map(team_counts)

# Rank teams by number of matches played (descending)
df['Rank'] = df['Matches_Played'].rank(method='first', ascending=False)

In [22]:
df['Rank'] = df['Rank'].astype(np.int16)

In [23]:
df.set_index('Rank', inplace=True)

In [24]:
df.sort_index(inplace=True)

In [25]:
df.head()
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 128 entries, 1 to 128
Data columns (total 35 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Team                             128 non-null    object
 1   Against                          128 non-null    object
 2   Group                            128 non-null    object
 3   Goal                             128 non-null    int64
 4   Possession (%)                   128 non-null    int64
 5   Inside Penalty Area              128 non-null    int64
 6   Outside Penalty Area             128 non-null    int64
 7   Assists                          128 non-null    int64
 8   Total Attempts                   128 non-null    int64
 9   On Target                        128 non-null    int64
 10  Off Target                       128 non-null    int64
 11  Target in Penalty                128 non-null    int64
 12  Target from Outside              128 non-null    int64
 13  Left Channel                     128 non-null    int64
 14  Left Inside Channel              128 non-null    int64
 15  Central Channel                  128 non-null    int64
 16  Right Inside Channel             128 non-null    int64
 17  Right Channel                    128 non-null    int64
 18  Receptions MD                    128 non-null    int64
 19  Receptions D                     128 non-null    int64
 20  Attempted Line Breaks            128 non-null    int64
 21  Completed Line Breaks            128 non-null    int64
 22  Attempted Defensive Line Breaks  128 non-null    int64
 23  Completed Defensive Line Breaks  128 non-null    int64
 24  Yellow Cards                     128 non-null    int64
 25  Fouls Against                    128 non-null    int64
 26  Offsides                         128 non-null    int64
 27  Passes                           128 non-null    int64
 28  Passes Completed                 128 non-null    int64
 29  Crosses                          128 non-null    int64
 30  Crosses Completed                128 non-null    int64
 31  Corners                          128 non-null    int64
 32  Free Kicks                       128 non-null    int64
 33  Penalties Scored                 128 non-null    int64
 34  Matches_Played                   128 non-null    int64
dtypes: int64(32), object(3)
memory usage: 35.2+ KB

## Questions on Titanic dataset.

You can get the dataset from [here](https://www.kaggle.com/competitions/titanic). This is the competition page on Kaggle. To download the dataset from here, I guess you have to register for the compition. So, do so and then download the dataset.

Also, for now you can use this url to read the dataset like before:
- dataset 1: https://docs.google.com/spreadsheets/d/e/2PACX-1vQjh5HzZ1N0SU7ME9ZQRzeVTaXaGsV97rU8R7eAcg53k27GTstJp9cRUOfr55go1GRRvTz1NwvyOnuh/pub?gid=1562145139&single=true&output=csv
- dataset 2: https://docs.google.com/spreadsheets/d/e/2PACX-1vQcPvQsSC9aNFogvbUG08nu0bGHlOclGYaOlhND_LE5Ff7ZnHQ5VYzAgpyT5XNklgiT54SsNgHePsUa/pub?gid=1656109608&single=true&output=csv

### `Q-5:` Do the below tasks:
1. With dataset 1, drop those records which only have missing values of the "Age" column permanently.

2. With the dataset 2, fill the missing values with 20 to the only "Age" column permanently.

In [ ]:
# code here

In [ ]:
dataset1 = pd.read_csv('/content/18_test - test.csv')
dataset2 = pd.read_csv('/content/18_train - train.csv')

In [ ]:
dataset1.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [ ]:
dataset1.dropna(subset = ['Age'],inplace=True)

In [ ]:
dataset1.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          245
Embarked         0
dtype: int64

In [ ]:
dataset2.iloc[411]

PassengerId                412
Survived                     0
Pclass                       3
Name           Hart, Mr. Henry
Sex                       male
Age                       20.0
SibSp                        0
Parch                        0
Ticket                  394140
Fare                    6.8583
Cabin                      NaN
Embarked                     Q
Name: 411, dtype: object

In [ ]:
dataset2['Age'].fillna(20,inplace = True )

/tmp/ipython-input-3900677290.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset2['Age'].fillna(20,inplace = True )

## Questions on IPL wala dataset

matches dataset = https://drive.google.com/file/d/1yKVUuexl6lIKuFQy7uIPgDgXhJ0L4SIg/view?usp=share_link

Code to directly use in colab
```
ipl_matches = "https://docs.google.com/spreadsheets/d/e/2PACX-1vRy2DUdUbaKx_Co9F0FSnIlyS-8kp4aKv_I0-qzNeghiZHAI_hw94gKG22XTxNJHMFnFVKsO4xWOdIs/pub?gid=1655759976&single=true&output=csv"

```

In [ ]:
df = pd.read_csv('/content/18_IPL_Matches_2008_2022.csv')

In [ ]:
df.head()

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan

In [ ]:
df['method'].unique()

array([nan, 'D/L'], dtype=object)

In [ ]:
df['WonBy'].unique()

array(['Wickets', 'Runs', 'SuperOver', 'NoResults'], dtype=object)

###`Q-6:` Make a dataframe of each team in IPL with details like - Team Name, Matches Played, Win%, Home Win%, Away Win%.
Show sorted dataframe on Win%

Replace old team name as new name before performing any tasks.
```
Delhi Daredevils ->Delhi Capitals
Kings XI Punjab -> Punjab Kings
Rising Pune Supergiants -> Rising Pune Supergiant
```

Note: Team1 represents Home team. Exclude not result matches.

In [ ]:
# code here

In [ ]:
mapping = {

  "Delhi Daredevils" : "Delhi Capitals",
  "Kings XI Punjab":"Punjab Kings",
  "Rising Pune Supergiants" : "Rising Pune Supergiant"

}

In [ ]:
df['Team1'] = df['Team1'].replace(mapping)

In [ ]:
df['Team2'] = df['Team2'].replace(mapping)

In [ ]:
df['WinningTeam'] = df['WinningTeam'].replace(mapping)

In [ ]:
Home_Ground_Mathces = df['Team1'].value_counts()

In [ ]:
Home_Ground_Mathces.sort_index()

Team1
Chennai Super Kings            111
Deccan Chargers                 39
Delhi Capitals                 114
Gujarat Lions                   16
Gujarat Titans                   7
Kochi Tuskers Kerala             7
Kolkata Knight Riders          105
Lucknow Super Giants             8
Mumbai Indians                 112
Pune Warriors                   23
Punjab Kings                   110
Rajasthan Royals                89
Rising Pune Supergiant          14
Royal Challengers Bangalore    126
Sunrisers Hyderabad             69
Name: count, dtype: int64

In [ ]:
Away_Matches = c2 = df['Team2'].value_counts()

In [ ]:
Away_Matches.sort_index()

Team2
Chennai Super Kings             97
Deccan Chargers                 36
Delhi Capitals                 110
Gujarat Lions                   14
Gujarat Titans                   9
Kochi Tuskers Kerala             7
Kolkata Knight Riders          118
Lucknow Super Giants             7
Mumbai Indians                 119
Pune Warriors                   23
Punjab Kings                   108
Rajasthan Royals               103
Rising Pune Supergiant          16
Royal Challengers Bangalore    100
Sunrisers Hyderabad             83
Name: count, dtype: int64

In [ ]:
Matches_played_by_each_team = (Home_Ground_Mathces + Away_Matches)

In [ ]:
Matches_played_by_each_team = Matches_played_by_each_team.sort_index()

In [ ]:
Matches_played_by_each_team

Chennai Super Kings            208
Deccan Chargers                 75
Delhi Capitals                 224
Gujarat Lions                   30
Gujarat Titans                  16
Kochi Tuskers Kerala            14
Kolkata Knight Riders          223
Lucknow Super Giants            15
Mumbai Indians                 231
Pune Warriors                   46
Punjab Kings                   218
Rajasthan Royals               192
Rising Pune Supergiant          30
Royal Challengers Bangalore    226
Sunrisers Hyderabad            152
Name: count, dtype: int64

In [ ]:
home_win_Percentage = (Home_Ground_Mathces / Matches_played_by_each_team)*100

In [ ]:
home_win_Percentage = home_win_Percentage.sort_index()

In [ ]:
away_home_percentage = (Away_Matches / Matches_played_by_each_team)*100

In [ ]:
away_home_percentage = away_home_percentage.sort_index()

In [ ]:
away_home_percentage

Chennai Super Kings            46.634615
Deccan Chargers                48.000000
Delhi Capitals                 49.107143
Gujarat Lions                  46.666667
Gujarat Titans                 56.250000
Kochi Tuskers Kerala           50.000000
Kolkata Knight Riders          52.914798
Lucknow Super Giants           46.666667
Mumbai Indians                 51.515152
Pune Warriors                  50.000000
Punjab Kings                   49.541284
Rajasthan Royals               53.645833
Rising Pune Supergiant         53.333333
Royal Challengers Bangalore    44.247788
Sunrisers Hyderabad            54.605263
Name: count, dtype: float64

In [ ]:
matches_won_by_each_team = df['WinningTeam'].value_counts()

In [ ]:
matches_won_by_each_team = matches_won_by_each_team.sort_index()

In [ ]:
matches_won_by_each_team

WinningTeam
Chennai Super Kings            121
Deccan Chargers                 29
Delhi Capitals                 103
Gujarat Lions                   13
Gujarat Titans                  12
Kochi Tuskers Kerala             6
Kolkata Knight Riders          114
Lucknow Super Giants             9
Mumbai Indians                 131
Pune Warriors                   12
Punjab Kings                   101
Rajasthan Royals                96
Rising Pune Supergiant          15
Royal Challengers Bangalore    109
Sunrisers Hyderabad             75
Name: count, dtype: int64

In [ ]:
win_percentage = ( matches_won_by_each_team / Matches_played_by_each_team ) * 100

In [ ]:
win_percentage

WinningTeam
Chennai Super Kings            58.173077
Deccan Chargers                38.666667
Delhi Capitals                 45.982143
Gujarat Lions                  43.333333
Gujarat Titans                 75.000000
Kochi Tuskers Kerala           42.857143
Kolkata Knight Riders          51.121076
Lucknow Super Giants           60.000000
Mumbai Indians                 56.709957
Pune Warriors                  26.086957
Punjab Kings                   46.330275
Rajasthan Royals               50.000000
Rising Pune Supergiant         50.000000
Royal Challengers Bangalore    48.230088
Sunrisers Hyderabad            49.342105
Name: count, dtype: float64

In [ ]:
temp_df = Home_Ground_Mathces.sort_index().reset_index()

In [ ]:
Team_Names = temp_df['Team1']

In [ ]:
Team_Names

0             Chennai Super Kings
1                 Deccan Chargers
2                  Delhi Capitals
3                   Gujarat Lions
4                  Gujarat Titans
5            Kochi Tuskers Kerala
6           Kolkata Knight Riders
7            Lucknow Super Giants
8                  Mumbai Indians
9                   Pune Warriors
10                   Punjab Kings
11               Rajasthan Royals
12         Rising Pune Supergiant
13    Royal Challengers Bangalore
14            Sunrisers Hyderabad
Name: Team1, dtype: object

In [ ]:
Info = pd.DataFrame(
    {
    # "Team Name" : Team_Names,
    "Matches Played" : Matches_played_by_each_team,
    "Win%" : win_percentage,
    "Home Win%" : home_win_Percentage,
    "Away Win%" : away_home_percentage
    },

)

In [ ]:
Info

                             Matches Played       Win%  Home Win%  Away Win%
Chennai Super Kings                     208  58.173077  53.365385  46.634615
Deccan Chargers                          75  38.666667  52.000000  48.000000
Delhi Capitals                          224  45.982143  50.892857  49.107143
Gujarat Lions                            30  43.333333  53.333333  46.666667
Gujarat Titans                           16  75.000000  43.750000  56.250000
Kochi Tuskers Kerala                     14  42.857143  50.000000  50.000000
Kolkata Knight Riders                   223  51.121076  47.085202  52.914798
Lucknow Super Giants                     15  60.000000  53.333333  46.666667
Mumbai Indians                          231  56.709957  48.484848  51.515152
Pune Warriors                            46  26.086957  50.000000  50.000000
Punjab Kings                            218  46.330275  50.458716  49.541284
Rajasthan Royals                        192  50.000000  46.354167  53.645833
Rising Pune Supergiant                   30  50.000000  46.666667  53.333333
Royal Challengers Bangalore             226  48.230088  55.752212  44.247788
Sunrisers Hyderabad                     152  49.342105  45.394737  54.605263

###`Q-7:` Venues with most "no result" matches.

In [ ]:
# code here

In [ ]:
df['WonBy'].unique()

array(['Wickets', 'Runs', 'SuperOver', 'NoResults'], dtype=object)

In [ ]:
new_df = df[df['WonBy'] == "NoResults"]

In [ ]:
Venues_with_most_NoResult_matches = new_df.value_counts('Venue')

In [ ]:
Venues_with_most_NoResult_matches

Venue
M Chinnaswamy Stadium    2
Feroz Shah Kotla         1
M.Chinnaswamy Stadium    1
Name: count, dtype: int64

###`Q-8:` Player with most appearance in final match.

`Team1Players` and `Team2Players` have all players name. It is not a list of players name instead it is str. So handle it as string.

Hint: split and strip will help; Make a series of all players in final and do value counts

In [ ]:
# code here

In [ ]:
new_df = df[df['MatchNumber'] == "Final"]

In [ ]:
players = new_df['Team1Players'] + new_df['Team2Players']

In [ ]:
players[0]

"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D Padikkal', 'SO Hetmyer', 'R Ashwin', 'R Parag', 'TA Boult', 'OC McCoy', 'M Prasidh Krishna', 'YS Chahal']['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pandya', 'DA Miller', 'R Tewatia', 'Rashid Khan', 'R Sai Kishore', 'LH Ferguson', 'Yash Dayal', 'Mohammed Shami']"

In [ ]:
import re

In [ ]:
# players = re.findall(r"'([^']+)'", players[0])

In [ ]:
# players

In [ ]:
players_list = players.str.findall(r"'([^']+)'").explode().dropna().tolist()

In [ ]:
players_list

['YBK Jaiswal',
 'JC Buttler',
 'SV Samson',
 'D Padikkal',
 'SO Hetmyer',
 'R Ashwin',
 'R Parag',
 'TA Boult',
 'OC McCoy',
 'M Prasidh Krishna',
 'YS Chahal',
 'WP Saha',
 'Shubman Gill',
 'MS Wade',
 'HH Pandya',
 'DA Miller',
 'R Tewatia',
 'Rashid Khan',
 'R Sai Kishore',
 'LH Ferguson',
 'Yash Dayal',
 'Mohammed Shami',
 'RD Gaikwad',
 'F du Plessis',
 'RV Uthappa',
 'MM Ali',
 'AT Rayudu',
 'MS Dhoni',
 'RA Jadeja',
 'DJ Bravo',
 'SN Thakur',
 'DL Chahar',
 'JR Hazlewood',
 'Shubman Gill',
 'VR Iyer',
 'N Rana',
 'SP Narine',
 'EJG Morgan',
 'KD Karthik',
 'Shakib Al Hasan',
 'RA Tripathi',
 'LH Ferguson',
 'Shivam Mavi',
 'CV Varun',
 'MP Stoinis',
 'S Dhawan',
 'AM Rahane',
 'SS Iyer',
 'RR Pant',
 'SO Hetmyer',
 'AR Patel',
 'K Rabada',
 'P Dubey',
 'R Ashwin',
 'A Nortje',
 'RG Sharma',
 'Q de Kock',
 'SA Yadav',
 'Ishan Kishan',
 'KA Pollard',
 'HH Pandya',
 'KH Pandya',
 'J Yadav',
 'NM Coulter-Nile',
 'TA Boult',
 'JJ Bumrah',
 'Q de Kock',
 'RG Sharma',
 'SA Yadav',
 'Ishan Kishan',
 'KH Pandya',
 'KA Pollard',
 'HH Pandya',
 'RD Chahar',
 'MJ McClenaghan',
 'JJ Bumrah',
 'SL Malinga',
 'F du Plessis',
 'SR Watson',
 'SK Raina',
 'AT Rayudu',
 'MS Dhoni',
 'DJ Bravo',
 'RA Jadeja',
 'SN Thakur',
 'DL Chahar',
 'Harbhajan Singh',
 'Imran Tahir',
 'SP Goswami',
 'S Dhawan',
 'KS Williamson',
 'Shakib Al Hasan',
 'YK Pathan',
 'DJ Hooda',
 'CR Brathwaite',
 'Rashid Khan',
 'B Kumar',
 'S Kaul',
 'Sandeep Sharma',
 'SR Watson',
 'F du Plessis',
 'SK Raina',
 'AT Rayudu',
 'MS Dhoni',
 'DJ Bravo',
 'RA Jadeja',
 'DL Chahar',
 'KV Sharma',
 'SN Thakur',
 'L Ngidi',
 'LMP Simmons',
 'PA Patel',
 'AT Rayudu',
 'RG Sharma',
 'KH Pandya',
 'KA Pollard',
 'HH Pandya',
 'KV Sharma',
 'MG Johnson',
 'JJ Bumrah',
 'SL Malinga',
 'AM Rahane',
 'RA Tripathi',
 'SPD Smith',
 'MS Dhoni',
 'MK Tiwary',
 'DT Christian',
 'Washington Sundar',
 'LH Ferguson',
 'A Zampa',
 'SN Thakur',
 'JD Unadkat',
 'CH Gayle',
 'V Kohli',
 'AB de Villiers',
 'KL Rahul',
 'SR Watson',
 'Sachin Baby',
 'STR Binny',
 'CJ Jordan',
 'Iqbal Abdulla',
 'S Aravind',
 'YS Chahal',
 'DA Warner',
 'S Dhawan',
 'MC Henriques',
 'Yuvraj Singh',
 'DJ Hooda',
 'BCJ Cutting',
 'NV Ojha',
 'Bipul Sharma',
 'B Kumar',
 'BB Sran',
 'Mustafizur Rahman',
 'LMP Simmons',
 'PA Patel',
 'RG Sharma',
 'KA Pollard',
 'AT Rayudu',
 'HH Pandya',
 'Harbhajan Singh',
 'J Suchith',
 'MJ McClenaghan',
 'R Vinay Kumar',
 'SL Malinga',
 'DR Smith',
 'MEK Hussey',
 'SK Raina',
 'MS Dhoni',
 'DJ Bravo',
 'P Negi',
 'F du Plessis',
 'RA Jadeja',
 'R Ashwin',
 'MM Sharma',
 'A Nehra',
 'RV Uthappa',
 'G Gambhir',
 'MK Pandey',
 'YK Pathan',
 'Shakib Al Hasan',
 'RN ten Doeschate',
 'SA Yadav',
 'PP Chawla',
 'SP Narine',
 'M Morkel',
 'UT Yadav',
 'V Sehwag',
 'M Vohra',
 'GJ Bailey',
 'WP Saha',
 'GJ Maxwell',
 'DA Miller',
 'AR Patel',
 'MG Johnson',
 'L Balaji',
 'Karanveer Singh',
 'P Awana',
 'MEK Hussey',
 'M Vijay',
 'SK Raina',
 'S Badrinath',
 'DJ Bravo',
 'RA Jadeja',
 'MS Dhoni',
 'JA Morkel',
 'CH Morris',
 'R Ashwin',
 'MM Sharma',
 'DR Smith',
 'AP Tare',
 'KD Karthik',
 'RG Sharma',
 'AT Rayudu',
 'KA Pollard',
 'Harbhajan Singh',
 'R Dhawan',
 'MG Johnson',
 'SL Malinga',
 'PP Ojha',
 'MS Bisla',
 'G Gambhir',
 'JH Kallis',
 'LR Shukla',
 'YK Pathan',
 'Shakib Al Hasan',
 'MK Tiwary',
 'R Bhatia',
 'Iqbal Abdulla',
 'SP Narine',
 'B Lee',
 'MEK Hussey',
 'M Vijay',
 'SK Raina',
 'MS Dhoni',
 'DJ Bravo',
 'RA Jadeja',
 'JA Morkel',
 'R Ashwin',
 'BW Hilfenhaus',
 'SB Jakati',
 'S Badrinath',
 'MEK Hussey',
 'M Vijay',
 'MS Dhoni',
 'SK Raina',
 'JA Morkel',
 'S Badrinath',
 'DJ Bravo',
 'WP Saha',
 'R Ashwin',
 'DE Bollinger',
 'SB Jakati',
 'MA Agarwal',
 'CH Gayle',
 'V Kohli',
 'AB de Villiers',
 'LA Pomersbach',
 'SS Tiwary',
 'DL Vettori',
 'A Mithun',
 'Z Khan',
 'J Syed Mohammad',
 'S Aravind',
 'M Vijay',
 'ML Hayden',
 'SK Raina',
 'S Badrinath',
 'MS Dhoni',
 'JA Morkel',
 'S Anirudha',
 'R Ashwin',
 'SB Jakati',
 'DE Bollinger',
 'M Muralitharan',
 'S Dhawan',
 'SR Tendulkar',
 'AM Nayar',
 'Harbhajan Singh',
 'AT Rayudu',
 'SS Tiwary',
 'JP Duminy',
 'KA Pollard',
 'Z Khan',
 'SL Malinga',
 'CRD Fernando',
 'JH Kallis',
 'MK Pandey',
 'RE van der Merwe',
 'R Dravid',
 'LRPL Taylor',
 'V Kohli',
 'MV Boucher',
 'RV Uthappa',
 'P Kumar',
 'R Vinay Kumar',
 'A Kumble',
 'AC Gilchrist',
 'HH Gibbs',
 'TL Suman',
 'A Symonds',
 'RG Sharma',
 'Y Venugopal Rao',
 'AA Bilakhia',
 'RJ Harris',
 'PP Ojha',
 'Harmeet Singh',
 'RP Singh',
 'PA Patel',
 'S Vidyut',
 'SK Raina',
 'JA Morkel',
 'MS Dhoni',
 'CK Kapugedera',
 'S Badrinath',
 'MS Gony',
 'L Balaji',
 'M Muralitharan',
 'M Ntini',
 'NK Patel',
 'SA Asnodkar',
 'Kamran Akmal',
 'SR Watson',
 'YK Pathan',
 'M Kaif',
 'RA Jadeja',
 'SK Warne',
 'Sohail Tanvir',
 'SK Trivedi',
 'MM Patel']

In [ ]:
players = players.apply(lambda x: re.findall(r"'([^']+)'", x))

In [ ]:
from collections import Counter

name_counts = Counter(name for row in players for name in row)

In [ ]:
name_counts = pd.Series(name_counts)

In [ ]:
Player_with_most_appearance_in_final_match = name_counts.sort_values(ascending = False).head()

In [ ]:
Player_with_most_appearance_in_final_match

MS Dhoni     10
SK Raina      8
AT Rayudu     7
DJ Bravo      7
RA Jadeja     7
dtype: int64

###`Q-9:` IPL Point Table

Make a function `point_table` which take `season` as parameter and show points table in non-ascendng order of points and in ascending order of team name.

For winning - 2 Ponits;
For loosing - 0 Point
For not result both team gets 1 points.

Make dataframe which will have
`TeamName` `MatchesPlayed` `MatchesWon` `NoResult` `Points`
make `TeamName` as index.

```
season parametr should be one of these->
['2022', '2021', '2020/21', '2019', '2018', '2017', '2016', '2015', '2014', '2013', '2012', '2011', '2009/10', '2009', '2007/08']
```

Output of two Top 2 in season 2022
```
TeamName    MatchesPlayed	MatchesWon	NoResult	Points

Gujarat Titans	    16	   12	       0	     24
Rajasthan Royals	  17	   10	       0	     20

```

In [ ]:
# code here

In [ ]:
points =(df[df['Season'] == '2022']['WinningTeam'].value_counts() ) * 2

In [ ]:
points

WinningTeam
Gujarat Titans                 24
Rajasthan Royals               20
Royal Challengers Bangalore    18
Lucknow Super Giants           18
Punjab Kings                   14
Delhi Capitals                 14
Kolkata Knight Riders          12
Sunrisers Hyderabad            12
Mumbai Indians                  8
Chennai Super Kings             8
Name: count, dtype: int64

In [ ]:
mapping = {

           '2020/21' : '2020',
           '2009/10' : '2010',
           '2007/08' : '2008'

}

In [ ]:
df['Season'] = df['Season'].replace(mapping)

In [ ]:
def print_table(season):

  point_table = (df[df['Season'] == season ]['WinningTeam'].value_counts()) * 2

  print(point_table)

In [ ]:
print_table('2012')

WinningTeam
Kolkata Knight Riders          24
Delhi Capitals                 22
Chennai Super Kings            20
Mumbai Indians                 20
Punjab Kings                   16
Royal Challengers Bangalore    16
Rajasthan Royals               14
Deccan Chargers                 8
Pune Warriors                   8
Name: count, dtype: int64

In [ ]:
# making the dataframe that will contain TeamName MatchesPlayed MatchesWon NoResult Points make TeamName as index.

In [ ]:
new_df = df[df['Season']=='2020']

In [ ]:
#Calculating total matches

In [ ]:
homeGroundMathces = new_df['Team1'].value_counts()

In [ ]:
awayGroundMatches = new_df['Team2'].value_counts()

In [ ]:
Total_matches = homeGroundMathces + awayGroundMatches

In [ ]:
Total_matches

Chennai Super Kings            14
Delhi Capitals                 17
Kolkata Knight Riders          14
Mumbai Indians                 16
Punjab Kings                   14
Rajasthan Royals               14
Royal Challengers Bangalore    15
Sunrisers Hyderabad            16
Name: count, dtype: int64

In [ ]:
# calculating total wins

In [ ]:
Mathces_won = new_df['WinningTeam'].value_counts()

In [ ]:
Mathces_won

WinningTeam
Mumbai Indians                 11
Delhi Capitals                  9
Sunrisers Hyderabad             8
Kolkata Knight Riders           7
Royal Challengers Bangalore     7
Chennai Super Kings             6
Rajasthan Royals                6
Punjab Kings                    6
Name: count, dtype: int64

In [ ]:
# calculating no_result

In [ ]:
new_df[new_df['WonBy'] == 'NoResults']

Empty DataFrame
Columns: [ID, City, Date, Season, MatchNumber, Team1, Team2, Venue, TossWinner, TossDecision, SuperOver, WinningTeam, WonBy, Margin, method, Player_of_Match, Team1Players, Team2Players, Umpire1, Umpire2]
Index: []

In [ ]:
# therse no matrch which ended as no result

In [ ]:
# calculating points

In [ ]:
points = Mathces_won * 2

In [ ]:
points

WinningTeam
Mumbai Indians                 22
Delhi Capitals                 18
Sunrisers Hyderabad            16
Kolkata Knight Riders          14
Royal Challengers Bangalore    14
Chennai Super Kings            12
Rajasthan Royals               12
Punjab Kings                   12
Name: count, dtype: int64

In [ ]:
Information = pd.DataFrame(
    {
        'Matches_played' : Total_matches,
        'Mathces_won' : Mathces_won,
        'points' : points
    }
)

In [ ]:
Information = Information.sort_values('points',ascending=False)

In [ ]:
Information['NoResult'] = 0

In [ ]:
Information

                             Matches_played  Mathces_won  points  NoResult
Mumbai Indians                           16           11      22         0
Delhi Capitals                           17            9      18         0
Sunrisers Hyderabad                      16            8      16         0
Kolkata Knight Riders                    14            7      14         0
Royal Challengers Bangalore              15            7      14         0
Chennai Super Kings                      14            6      12         0
Rajasthan Royals                         14            6      12         0
Punjab Kings                             14            6      12         0

###`Q-10:` IPL Point Table cont.
Extend the above IPL Point Table with an extra column as `SeasonPosition`

Team below top 4 after sorting on `Points` and then on `TeamName` Will have same `SeasonPosition` as there rank. use rank function.

Teams in Top four will have `SeasonPosition` as:
```
    'Winner' - Team won final
    'Runner' - Team lost Final
    3 - Losing Team in Qualifier2
    4 - Losing Team in Eliminator
```

For changing value of pariticular cell use `df.at[row_index, col_label] = value`

Output of two Top 2 in season 2022. Your result should have all teams.
```
TeamName    MatchesPlayed	MatchesWon	NoResult	Points   SeasonPosition

Gujarat Titans	    16	   12	       0	     24         Winner
Rajasthan Royals	  17	   10	       0	     20         Runner

```

Note: If you try to chnage value of view of any dataframe a warnig will be shown. To avoid it, make a copy of the dataframe you want to change in by `df.copy()`

In [ ]:
# code here

In [ ]:
Information['points'].rank(method = 'dense').astype(int)

Mumbai Indians                 5
Delhi Capitals                 4
Sunrisers Hyderabad            3
Kolkata Knight Riders          2
Royal Challengers Bangalore    2
Chennai Super Kings            1
Rajasthan Royals               1
Punjab Kings                   1
Name: points, dtype: int64

In [ ]:
Information['SeasonPosition'] = range(1, len(Information) + 1)

In [ ]:
Information

,Matches_played,Mathces_won,points,NoResult,SeasonPosition
Mumbai Indians,16,11,22,0,Runner up
Delhi Capitals,17,9,18,0,2
Sunrisers Hyderabad,16,8,16,0,3
Kolkata Knight Riders,14,7,14,0,4
Royal Challengers Bangalore,15,7,14,0,5
Chennai Super Kings,14,6,12,0,6
Rajasthan Royals,14,6,12,0,7
Punjab Kings,14,6,12,0,8

In [ ]:
Information.at['Mumbai Indians', "SeasonPosition"] = 'Winner'

In [ ]:
Information.at['Delhi Capitals', "SeasonPosition"] = 'Runner up'

In [ ]:
Information

,Matches_played,Mathces_won,points,NoResult,SeasonPosition
Mumbai Indians,16,11,22,0,Winner
Delhi Capitals,17,9,18,0,Runner up
Sunrisers Hyderabad,16,8,16,0,3
Kolkata Knight Riders,14,7,14,0,4
Royal Challengers Bangalore,15,7,14,0,5
Chennai Super Kings,14,6,12,0,6
Rajasthan Royals,14,6,12,0,7
Punjab Kings,14,6,12,0,8