In [ ]:
import pandas as pd
import numpy as np
import re

pd.options.display.max_columns = None

### `Question-1:`

The dataset is based on NFTs. This is quite large. So, when you will read the dataset, you have to wait. The link of the dataset: https://tinyurl.com/2pfhncqw

Your task is to make a pivote table by using the columns "verification_status", "contract_type", "rarity_score" and "last_sale_price" to find out the total values.

In [ ]:
# code here

### `Question-2:`

You are given a dataset about the cars' price and miles driven of different cars throughout the different years. The link of the dataset: https://tinyurl.com/2r24n45l. Your tasks are
- make a pivot table of the brands (the required brands are given below) from the "Year" 2018 to the year 2022 in which the "Price" is shown as average values and "Miles" are in median values. In this pivote table, every row represents a particular brand and each column represents either average "Price" of a partucular year or median values of "Miles" of a particular year.
- At the end plot a kde chart for the "Price" and "Miles" by using your pivot table.

There are some challenges to solve this task:
- There is no column that is represented to the brand name of the car. You have to find out on your own.
- Some values of "Years" column are misleading. You have to reset this column too that every value should tell a valid meaning.

In [ ]:
# code here

### `Question-3:`

You are given a dataset of **Daily Power Generation in India** of regional wise of all Power Stations. Link of the dataset: https://tinyurl.com/2nq6kugt

Task
- In this dataset, there are many columns. Two of them are `Actual(MU)` and `Excess(+) / Shortfall (-)`. `Actual(MU)` represents the actual power generation. `Excess(+) / Shortfall (-)` tells is that generated power is excess or shortfall for that particular day of a power station. You have to find out what should be the actual power generation required for that day by the power stations that there would not be any excess or shorfall power. For the result, make a new column.
- Find out the month of the day and store it as a new column.
- Find out top 10 frequently appeared power stations in this dataframe.
- Next create a pivot table of which every row represents a power station and every column represents a month in a order. Like January, February, March...
- It is hard to get inside if you look through the only pivot table. So plot the pivot table.

In [ ]:
# code here

###`Q-4` You are given a file `question-answer.csv`. Your task is to make a dataframe from it with two columns - `question` and `answers`.

* Questions in the file start from `Q<number>`; E.g.  `Q1` denotes question no. `1`
* Answers starts from `Ans<number>`; Eg. `Ans1` denotes answer of question no `1`
* MAke sure you look at columns name carefully

CSV File - "https://drive.google.com/file/d/10rmV3XrVtzpDTtYZF3UtCdcU0ajBJjGY/view?usp=share_link"

In [ ]:
# code here

###`Q-5`: Print Question and answer of those questions which does not contains any question mark (`?`).

In [ ]:
# code here

###`Q 6-10` LOG and EMPLOYEE
6. Show `activity` details month wise. Show count for each `activity`
7. Find employee who did most `activity` in January month.
8. Employee who have worked most no of times on Weekends.
9. Which activity is logged most on buisness days.
10. Week Days wise activity table.
```
log_file = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vT-OMrmmNdOTM-B5f5F1EpCutMVG230UZiLvqlsg0NIKUKR3yrqiI2r1pEX-LvSEk-3WwySPYtvbBC-/pub?gid=1937029224&single=true&output=csv")
employee = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vQ5AuFqRjSZVBKm5zyDxquX6utubq1DJKkYDI70vjeidAnyAu70KMSYpMYzeVSNVTeUIJBpfF6jU5E6/pub?gid=798824749&single=true&output=csv")

```

Note(for common field):- Employee file has `EMPLOYEE_ID` and LOG file has `emp_id`

In [1]:
import numpy as np
import pandas as pd

In [2]:
# code here
log_file = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vT-OMrmmNdOTM-B5f5F1EpCutMVG230UZiLvqlsg0NIKUKR3yrqiI2r1pEX-LvSEk-3WwySPYtvbBC-/pub?gid=1937029224&single=true&output=csv")
employee = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vQ5AuFqRjSZVBKm5zyDxquX6utubq1DJKkYDI70vjeidAnyAu70KMSYpMYzeVSNVTeUIJBpfF6jU5E6/pub?gid=798824749&single=true&output=csv")

In [3]:
log_file.head()

   Log_ID          dt   dept  emp_id    activity       eqpt
0    1000  2022-01-07  Dept6     115    Cleaning        UPS
1    1001  2022-01-08  Dept4     105    Cleaning  Generator
2    1002  2022-01-09  Dept3     112  Inspection        CPU
3    1003  2022-01-10  Dept4     120  Inspection        UPS
4    1004  2022-01-11  Dept3     138    Checking    Battery

In [4]:
employee.head()

   EMPLOYEE_ID FIRST_NAME LAST_NAME     EMAIL
0          100     Steven      King     SKING
1          101      Neena   Kochhar  NKOCHHAR
2          102        Lex   De Haan   LDEHAAN
3          103  Alexander    Hunold   AHUNOLD
4          104      Bruce     Ernst    BERNST

In [5]:
log_file.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Log_ID    365 non-null    int64
 1   dt        365 non-null    object
 2   dept      365 non-null    object
 3   emp_id    365 non-null    int64
 4   activity  365 non-null    object
 5   eqpt      365 non-null    object
dtypes: int64(2), object(4)
memory usage: 17.2+ KB

In [6]:
log_file['dt'] = pd.to_datetime(log_file['dt'])

In [7]:
log_file.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Log_ID    365 non-null    int64
 1   dt        365 non-null    datetime64[ns]
 2   dept      365 non-null    object
 3   emp_id    365 non-null    int64
 4   activity  365 non-null    object
 5   eqpt      365 non-null    object
dtypes: datetime64[ns](1), int64(2), object(3)
memory usage: 17.2+ KB

In [8]:
log_file.head()

   Log_ID         dt   dept  emp_id    activity       eqpt
0    1000 2022-01-07  Dept6     115    Cleaning        UPS
1    1001 2022-01-08  Dept4     105    Cleaning  Generator
2    1002 2022-01-09  Dept3     112  Inspection        CPU
3    1003 2022-01-10  Dept4     120  Inspection        UPS
4    1004 2022-01-11  Dept3     138    Checking    Battery

In [9]:
log_file['month_name'] = log_file['dt'].dt.month_name()

In [10]:
activity_details = log_file.groupby(['month_name','activity'])['activity'].count()

In [11]:
activity_details = log_file.groupby(['month_name','activity'])['activity'].count()

In [12]:
activity_details.head(25).sort_index()

month_name  activity
April       Checking       5
            Cleaning      11
            Inspection     9
            Repair         5
August      Checking       8
            Cleaning      10
            Inspection     9
            Repair         4
December    Checking       6
            Cleaning       7
            Inspection    12
            Repair         6
February    Checking       7
            Cleaning       7
            Inspection     4
            Repair        10
January     Checking       7
            Cleaning      10
            Inspection     9
            Repair         5
July        Checking       6
            Cleaning       6
            Inspection    14
            Repair         5
June        Checking       5
Name: activity, dtype: int64

In [57]:
# Q) 6

In [63]:
new_df = log_file.merge(employee , left_on='emp_id',right_on='EMPLOYEE_ID' , how='inner')

In [26]:
new_df

,Log_ID,dt,dept,emp_id,activity,eqpt,month_name,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL
0,1000,2022-01-07,Dept6,115,Cleaning,UPS,January,115,Alexander,Khoo,AKHOO
1,1001,2022-01-08,Dept4,105,Cleaning,Generator,January,105,David,Austin,DAUSTIN
2,1002,2022-01-09,Dept3,112,Inspection,CPU,January,112,NaN,Urman,JMURMAN
3,1003,2022-01-10,Dept4,120,Inspection,UPS,January,120,Matthew,Weiss,MWEISS
4,1004,2022-01-11,Dept3,138,Checking,Battery,January,138,Stephen,Stiles,SSTILES
...,...,...,...,...,...,...,...,...,...,...,...
290,1360,2023-01-02,Dept2,122,Repair,AC,January,122,Payam,Kaufling,PKAUFLING
291,1361,2023-01-03,Dept4,116,Checking,Server,January,116,Shelli,Baida,SBAIDA
292,1362,2023-01-04,Dept4,110,Checking,CPU,January,110,John,Chen,JCHEN
293,1363,2023-01-05,Dept4,102,Inspection,AC,January,102,Lex,De Haan,LDEHAAN
294,1364,2023-01-06,Dept3,128,Cleaning,AC,January,128,Steven,Markle,SMARKLE

In [30]:
new_df = new_df[new_df['month_name'] == 'January']

In [31]:
new_df

,Log_ID,dt,dept,emp_id,activity,eqpt,month_name,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL
0,1000,2022-01-07,Dept6,115,Cleaning,UPS,January,115,Alexander,Khoo,AKHOO
1,1001,2022-01-08,Dept4,105,Cleaning,Generator,January,105,David,Austin,DAUSTIN
2,1002,2022-01-09,Dept3,112,Inspection,CPU,January,112,NaN,Urman,JMURMAN
3,1003,2022-01-10,Dept4,120,Inspection,UPS,January,120,Matthew,Weiss,MWEISS
4,1004,2022-01-11,Dept3,138,Checking,Battery,January,138,Stephen,Stiles,SSTILES
5,1006,2022-01-13,Dept3,116,Repair,Pump,January,116,Shelli,Baida,SBAIDA
6,1007,2022-01-14,Dept4,131,Repair,Server,January,131,James,Marlow,JAMRLOW
7,1009,2022-01-16,Dept3,120,Inspection,CPU,January,120,Matthew,Weiss,MWEISS
8,1012,2022-01-19,Dept2,119,Cleaning,Server,January,119,Karen,Colmenares,KCOLMENA
9,1013,2022-01-20,Dept6,132,Inspection,Generator,January,132,NaN,Olson,TJOLSON
10,1014,2022-01-21,Dept4,127,Checking,Battery,January,127,James,Landry,JLANDRY
11,1015,2022-01-22,Dept4,107,Cleaning,Pump,January,107,Diana,Lorentz,DLORENTZ
12,1016,2022-01-23,Dept2,109,Cleaning,Generator,January,109,Daniel,Faviet,DFAVIET
13,1017,2022-01-24,Dept3,122,Inspection,CPU,January,122,Payam,Kaufling,PKAUFLING
14,1018,2022-01-25,Dept1,133,Repair,Fan,January,133,Jason,Mallin,JMALLIN
15,1019,2022-01-26,Dept2,108,Checking,UPS,January,108,Nancy,Greenberg,NGREENBE
16,1020,2022-01-27,Dept1,135,Inspection,Generator,January,135,Ki,Gee,KGEE
17,1021,2022-01-28,Dept3,112,Cleaning,AC,January,112,NaN,Urman,JMURMAN
18,1022,2022-01-29,Dept3,102,Checking,AC,January,102,Lex,De Haan,LDEHAAN
19,1023,2022-01-30,Dept6,124,Repair,AC,January,124,Kevin,Mourgos,KMOURGOS
20,1024,2022-01-31,Dept1,135,Cleaning,Server,January,135,Ki,Gee,KGEE
289,1359,2023-01-01,Dept3,122,Cleaning,Pump,January,122,Payam,Kaufling,PKAUFLING
290,1360,2023-01-02,Dept2,122,Repair,AC,January,122,Payam,Kaufling,PKAUFLING
291,1361,2023-01-03,Dept4,116,Checking,Server,January,116,Shelli,Baida,SBAIDA
292,1362,2023-01-04,Dept4,110,Checking,CPU,January,110,John,Chen,JCHEN
293,1363,2023-01-05,Dept4,102,Inspection,AC,January,102,Lex,De Haan,LDEHAAN
294,1364,2023-01-06,Dept3,128,Cleaning,AC,January,128,Steven,Markle,SMARKLE

In [36]:
new_df.groupby('emp_id')['emp_id'].count().sort_values(ascending=False).head(1)

emp_id
122    3
Name: emp_id, dtype: int64

In [51]:
first = new_df[new_df['emp_id'] == 122].head(1)[['FIRST_NAME','LAST_NAME']].values[0][0]

In [52]:
last = new_df[new_df['emp_id'] == 122].head(1)[['FIRST_NAME','LAST_NAME']].values[0][1]

In [55]:
employee_name = first +" " + last

In [58]:
employee_name

'Payam Kaufling'

In [60]:
# Q.8 employee who works most on weekends

In [64]:
temp = log_file.merge(employee , left_on='emp_id',right_on='EMPLOYEE_ID' , how='inner')

In [ ]:
temp['dt'].dt

0      4
1      5
2      6
3      0
4      1
      ..
290    0
291    1
292    2
293    3
294    4
Name: dt, Length: 295, dtype: int32

### `Q-11`:

1. There are missing value in first name of employee. Fill it using email and last name field.

> E.g- `email` -> JMURMAN and `last_name` -> 'Urman' -> so make it's first name as 'JM', Sort of (Email- lastname).

> Email is constructed from initials of first name concate with lastname. Your Task is to fill first name initials in missing data.

2. You can see email field don't have any domain name. Change this to full email addreess with domain as 'campusx.com'.
E.g- Email field -> `JMURMAN`  result -> `JMURMAN@CAMPUSX.COM`

3. Show Full Name of all the employees whose name starts with 'A' and has done any of these activity ['Incpection', 'Cleaning', 'Checking]

In [ ]:
# code here