# Real World Site

In [1]:
import pandas as pd
from bs4 import BeautifulSoup
import requests

In [3]:
url = "https://news.ycombinator.com/"

In [4]:
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36",
    "Accept-Language": "en-US,en;q=0.9",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
}

In [5]:
response = requests.get(url , headers = headers)

In [6]:
response.raise_for_status()

In [7]:
response.status_code

200

In [8]:
soup = BeautifulSoup(response.text , "html.parser")

In [9]:
# class="titleline"
item = soup.find("span", class_="titleline").find("a")

In [10]:
title1 = item.text.strip()

In [11]:
rank = soup.find("span", class_="rank").text

In [12]:
rank

'1.'

In [13]:
titles_all = soup.find_all("span", class_="titleline")

In [14]:
for t in titles_all:
    item = t.find("a").text
    print(item)

Building an HTML-first site doubled our users overnight
AMA: I'm Eric Ries (The Lean Startup) & Author of New Bestseller Incorruptible
PgDog is funded and coming to a database near you
Apache Burr: Build reliable AI agents and applications
Mercedes‑Benz starts large‑scale production of electric axial flux motor
GitHub Authentication issues related to API requests
macOS Container Machines
All 9,300 Japanese train station, animated by the year it opened (1872–2026)
Claude Fable 5
Buy a train, bridge or tracks from the Swiss Railway
US Consumer Price Index up 4.2%
Who Runs Your Rust Future? Hands-On Intro to Async Rust
The Last Evolution, by John W Campbell Jr. (1932)
'They take you out of life, out of time': a journey into Spain's cave paintings
Smudging the game disc to make speedrunning 'SpongeBob' faster
AWS Bedrock to require sharing data with Anthropic for Mythos and future models
Reviving Papers with Code
Ask HN: Are most corporate SWE jobs performative?
Hacking for Defense Stanford 2026 – Lessons Learned Presentations
The iPad was on Tailscale: a WebRTC debugging story
Upcoming breaking changes for npm v12
I Hate (Most) Keyboard 'Fn' Keys
A Server Called Mercury
Magnetoelectric antennas could transform how underwater robots talk
Chrome is looking to permanently drop MV2 extension
Notes on DeepSeek
German ruling declares Google liable for false answers in AI Overviews
RIP software hackathons. Long live the hardware hackathon
Rich Sutton on AI creativity and discovery
Surprise, pay $1000

In [66]:
# class="athing submission"

In [15]:
# Testing
allcotent = soup.find_all("tr" , class_=["athing", "submission"])

In [16]:
allcontent

[<tr class="athing submission" id="48475483"><td align="right" class="title" valign="top"><span class="rank">1.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48475483&amp;how=up&amp;goto=news" id="up_48475483"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://mohkohn.co.uk/writing/html-first/">Building an HTML-first site doubled our users overnight</a><span class="sitebit comhead"> (<a href="from?site=mohkohn.co.uk"><span class="sitestr">mohkohn.co.uk</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48477135"><td align="right" class="title" valign="top"><span class="rank">2.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48477135&amp;how=up&amp;goto=news" id="up_48477135"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="item?id=48477135">AMA: I'm Eric Ries (The Lean Startup) &amp; Author of New Bestseller Incorruptible</a></span></td></tr>,
 <tr class="athing submission" id="48476466"><td align="right" class="title" valign="top"><span class="rank">3.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48476466&amp;how=up&amp;goto=news" id="up_48476466"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://pgdog.dev/blog/our-funding-announcement">PgDog is funded and coming to a database near you</a><span class="sitebit comhead"> (<a href="from?site=pgdog.dev"><span class="sitestr">pgdog.dev</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48477400"><td align="right" class="title" valign="top"><span class="rank">4.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48477400&amp;how=up&amp;goto=news" id="up_48477400"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://burr.apache.org/">Apache Burr: Build reliable AI agents and applications</a><span class="sitebit comhead"> (<a href="from?site=apache.org"><span class="sitestr">apache.org</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48472877"><td align="right" class="title" valign="top"><span class="rank">5.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48472877&amp;how=up&amp;goto=news" id="up_48472877"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://media.mercedes-benz.com/en/article/bebac2af-acdc-465a-9538-adb0bf3d8ccf">Mercedes‑Benz starts large‑scale production of electric axial flux motor</a><span class="sitebit comhead"> (<a href="from?site=mercedes-benz.com"><span class="sitestr">mercedes-benz.com</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48477851"><td align="right" class="title" valign="top"><span class="rank">6.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48477851&amp;how=up&amp;goto=news" id="up_48477851"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://www.githubstatus.com/incidents/fcj3088jg1wx">GitHub Authentication issues related to API requests</a><span class="sitebit comhead"> (<a href="from?site=githubstatus.com"><span class="sitestr">githubstatus.com</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48469658"><td align="right" class="title" valign="top"><span class="rank">7.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48469658&amp;how=up&amp;goto=news" id="up_48469658"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://github.com/apple/container/blob/main/docs/container-machine.md">macOS Container Machines</a><span class="sitebit comhead"> (<a href="from?site=github.com/apple"><span class="sitestr">github.com/apple</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48475100"><td align="right" class="title" valign="top"><span class="rank">8.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48475100&amp;how=up&amp;goto=news" id="up_48475100"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://jivx.com/eki">All 9,300 Japanese train station, animated by the year it opened (1872–2026)</a><span class="sitebit comhead"> (<a href="from?site=jivx.com"><span class="sitestr">jivx.com</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48463808"><td align="right" class="title" valign="top"><span class="rank">9.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48463808&amp;how=up&amp;goto=news" id="up_48463808"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://www.anthropic.com/news/claude-fable-5-mythos-5">Claude Fable 5</a><span class="sitebit comhead"> (<a href="from?site=anthropic.com"><span class="sitestr">anthropic.com</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48442932"><td align="right" class="title" valign="top"><span class="rank">10.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48442932&amp;how=up&amp;goto=news" id="up_48442932"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://sbbresale.ch/">Buy a train, bridge or tracks from the Swiss Railway</a><span class="sitebit comhead"> (<a href="from?site=sbbresale.ch"><span class="sitestr">sbbresale.ch</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48477551"><td align="right" class="title" valign="top"><span class="rank">11.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48477551&amp;how=up&amp;goto=news" id="up_48477551"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://www.bls.gov/news.release/cpi.nr0.htm">US Consumer Price Index up 4.2%</a><span class="sitebit comhead"> (<a href="from?site=bls.gov"><span class="sitestr">bls.gov</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48445702"><td align="right" class="title" valign="top"><span class="rank">12.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48445702&amp;how=up&amp;goto=news" id="up_48445702"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://aibodh.com/posts/async-rust-chapter-1-hands-on-intro-to-async-rust/">Who Runs Your Rust Future? Hands-On Intro to Async Rust</a><span class="sitebit comhead"> (<a href="from?site=aibodh.com"><span class="sitestr">aibodh.com</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48478285"><td align="right" class="title" valign="top"><span class="rank">13.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48478285&amp;how=up&amp;goto=news" id="up_48478285"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://www.gutenberg.org/files/27462/27462-h/27462-h.htm" rel="nofollow">The Last Evolution, by John W Campbell Jr. (1932)</a><span class="sitebit comhead"> (<a href="from?site=gutenberg.org"><span class="sitestr">gutenberg.org</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48447378"><td align="right" class="title" valign="top"><span class="rank">14.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48447378&amp;how=up&amp;goto=news" id="up_48447378"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://www.theguardian.com/science/2026/jun/02/journey-into-spain-palaeolithic-cave-paintings-altamira">'They take you out of life, out of time': a journey into Spain's cave paintings</a><span class="sitebit comhead"> (<a href="from?site=theguardian.com"><span class="sitestr">theguardian.com</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48470578"><td align="right" class="title" valign="top"><span class="rank">15.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48470578&amp;how=up&amp;goto=news" id="up_48470578"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://www.inverse.com/input/gaming/the-dirty-secret-that-makes-speedrunning-on-spongebob-a-lot-faster">Smudging the game disc to make speedrunning 'SpongeBob' faster</a><span class="sitebit comhead"> (<a href="from?site=inverse.com"><span class="sitestr">inverse.com</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48473166"><td align="right" class="title" valign="top"><span class="rank">16.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48473166&amp;how=up&amp;goto=news" id="up_48473166"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="item?id=48473166">AWS Bedrock to require sharing data with Anthropic for Mythos and future models</a></span></td></tr>,
 <tr class="athing submission" id="48443644"><td align="right" class="title" valign="top"><span class="rank">17.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48443644&amp;how=up&amp;goto=news" id="up_48443644"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://paperswithcode.co/">Reviving Papers with Code</a><span class="sitebit comhead"> (<a href="from?site=paperswithcode.co"><span class="sitestr">paperswithcode.co</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48475871"><td align="right" class="title" valign="top"><span class="rank">18.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48475871&amp;how=up&amp;goto=news" id="up_48475871"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="item?id=48475871">Ask HN: Are most corporate SWE jobs performative?</a></span></td></tr>,
 <tr class="athing submission" id="48451789"><td align="right" class="title" valign="top"><span class="rank">19.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48451789&amp;how=up&amp;goto=news" id="up_48451789"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://steveblank.com/2026/06/08/g-for-defense-stanford-2026-lessons-learned-presentations/">Hacking for Defense Stanford 2026 – Lessons Learned Presentations</a><span class="sitebit comhead"> (<a href="from?site=steveblank.com"><span class="sitestr">steveblank.com</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48477589"><td align="right" class="title" valign="top"><span class="rank">20.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48477589&amp;how=up&amp;goto=news" id="up_48477589"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://p2claw.com/blog/2026-06-09-the-ipad-was-on-tailscale/" rel="nofollow">The iPad was on Tailscale: a WebRTC debugging story</a><span class="sitebit comhead"> (<a href="from?site=p2claw.com"><span class="sitestr">p2claw.com</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48467705"><td align="right" class="title" valign="top"><span class="rank">21.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48467705&amp;how=up&amp;goto=news" id="up_48467705"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://github.blog/changelog/2026-06-09-upcoming-breaking-changes-for-npm-v12/">Upcoming breaking changes for npm v12</a><span class="sitebit comhead"> (<a href="from?site=github.blog"><span class="sitestr">github.blog</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48475938"><td align="right" class="title" valign="top"><span class="rank">22.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48475938&amp;how=up&amp;goto=news" id="up_48475938"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://danq.me/2026/06/09/fn-keys/">I Hate (Most) Keyboard 'Fn' Keys</a><span class="sitebit comhead"> (<a href="from?site=danq.me"><span class="sitestr">danq.me</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48427324"><td align="right" class="title" valign="top"><span class="rank">23.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48427324&amp;how=up&amp;goto=news" id="up_48427324"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://kennethreitz.org/essays/2026-06-05-a_server_called_mercury" rel="nofollow">A Server Called Mercury</a><span class="sitebit comhead"> (<a href="from?site=kennethreitz.org"><span class="sitestr">kennethreitz.org</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48433525"><td align="right" class="title" valign="top"><span class="rank">24.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48433525&amp;how=up&amp;goto=news" id="up_48433525"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://newatlas.com/engineering/magnetoelectric-antennas-submarine-robots-communications/">Magnetoelectric antennas could transform how underwater robots talk</a><span class="sitebit comhead"> (<a href="from?site=newatlas.com"><span class="sitestr">newatlas.com</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48471970"><td align="right" class="title" valign="top"><span class="rank">25.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48471970&amp;how=up&amp;goto=news" id="up_48471970"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://www.neowin.net/news/google-chrome-is-killing-all-ublock-origin-bypasses-microsoft-edge-opera-to-follow/">Chrome is looking to permanently drop MV2 extension</a><span class="sitebit comhead"> (<a href="from?site=neowin.net"><span class="sitestr">neowin.net</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48476474"><td align="right" class="title" valign="top"><span class="rank">26.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48476474&amp;how=up&amp;goto=news" id="up_48476474"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://twitter.com/NikoMcCarty/status/2064686557400100884">Notes on DeepSeek</a><span class="sitebit comhead"> (<a href="from?site=twitter.com/nikomccarty"><span class="sitestr">twitter.com/nikomccarty</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48470248"><td align="right" class="title" valign="top"><span class="rank">27.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48470248&amp;how=up&amp;goto=news" id="up_48470248"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://the-decoder.com/landmark-german-ruling-declares-googles-ai-overviews-are-googles-own-words-and-makes-it-liable-for-false-answers/">German ruling declares Google liable for false answers in AI Overviews</a><span class="sitebit comhead"> (<a href="from?site=the-decoder.com"><span class="sitestr">the-decoder.com</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48468766"><td align="right" class="title" valign="top"><span class="rank">28.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48468766&amp;how=up&amp;goto=news" id="up_48468766"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://blog.oscars.dev/posts/rip-software-hackathons-long-live-the-hardware-hackathon/">RIP software hackathons. Long live the hardware hackathon</a><span class="sitebit comhead"> (<a href="from?site=oscars.dev"><span class="sitestr">oscars.dev</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48470581"><td align="right" class="title" valign="top"><span class="rank">29.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48470581&amp;how=up&amp;goto=news" id="up_48470581"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://twitter.com/RichardSSutton/status/2061216087744946656">Rich Sutton on AI creativity and discovery</a><span class="sitebit comhead"> (<a href="from?site=twitter.com/richardssutton"><span class="sitestr">twitter.com/richardssutton</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48468370"><td align="right" class="title" valign="top"><span class="rank">30.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48468370&amp;how=up&amp;goto=news" id="up_48468370"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://forestwalk.ai/blog/surprise-blacksmith-costs/">Surprise, pay $1000</a><span class="sitebit comhead"> (<a href="from?site=forestwalk.ai"><span class="sitestr">forestwalk.ai</span></a>)</span></span></td></tr>]

In [17]:
allcontent = soup.select("tr.athing.submission")

In [18]:
allcontent

[<tr class="athing submission" id="48475483"><td align="right" class="title" valign="top"><span class="rank">1.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48475483&amp;how=up&amp;goto=news" id="up_48475483"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://mohkohn.co.uk/writing/html-first/">Building an HTML-first site doubled our users overnight</a><span class="sitebit comhead"> (<a href="from?site=mohkohn.co.uk"><span class="sitestr">mohkohn.co.uk</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48477135"><td align="right" class="title" valign="top"><span class="rank">2.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48477135&amp;how=up&amp;goto=news" id="up_48477135"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="item?id=48477135">AMA: I'm Eric Ries (The Lean Startup) &amp; Author of New Bestseller Incorruptible</a></span></td></tr>,
 <tr class="athing submission" id="48476466"><td align="right" class="title" valign="top"><span class="rank">3.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48476466&amp;how=up&amp;goto=news" id="up_48476466"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://pgdog.dev/blog/our-funding-announcement">PgDog is funded and coming to a database near you</a><span class="sitebit comhead"> (<a href="from?site=pgdog.dev"><span class="sitestr">pgdog.dev</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48477400"><td align="right" class="title" valign="top"><span class="rank">4.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48477400&amp;how=up&amp;goto=news" id="up_48477400"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://burr.apache.org/">Apache Burr: Build reliable AI agents and applications</a><span class="sitebit comhead"> (<a href="from?site=apache.org"><span class="sitestr">apache.org</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48472877"><td align="right" class="title" valign="top"><span class="rank">5.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48472877&amp;how=up&amp;goto=news" id="up_48472877"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://media.mercedes-benz.com/en/article/bebac2af-acdc-465a-9538-adb0bf3d8ccf">Mercedes‑Benz starts large‑scale production of electric axial flux motor</a><span class="sitebit comhead"> (<a href="from?site=mercedes-benz.com"><span class="sitestr">mercedes-benz.com</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48477851"><td align="right" class="title" valign="top"><span class="rank">6.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48477851&amp;how=up&amp;goto=news" id="up_48477851"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://www.githubstatus.com/incidents/fcj3088jg1wx">GitHub Authentication issues related to API requests</a><span class="sitebit comhead"> (<a href="from?site=githubstatus.com"><span class="sitestr">githubstatus.com</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48469658"><td align="right" class="title" valign="top"><span class="rank">7.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48469658&amp;how=up&amp;goto=news" id="up_48469658"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://github.com/apple/container/blob/main/docs/container-machine.md">macOS Container Machines</a><span class="sitebit comhead"> (<a href="from?site=github.com/apple"><span class="sitestr">github.com/apple</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48475100"><td align="right" class="title" valign="top"><span class="rank">8.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48475100&amp;how=up&amp;goto=news" id="up_48475100"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://jivx.com/eki">All 9,300 Japanese train station, animated by the year it opened (1872–2026)</a><span class="sitebit comhead"> (<a href="from?site=jivx.com"><span class="sitestr">jivx.com</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48463808"><td align="right" class="title" valign="top"><span class="rank">9.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48463808&amp;how=up&amp;goto=news" id="up_48463808"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://www.anthropic.com/news/claude-fable-5-mythos-5">Claude Fable 5</a><span class="sitebit comhead"> (<a href="from?site=anthropic.com"><span class="sitestr">anthropic.com</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48442932"><td align="right" class="title" valign="top"><span class="rank">10.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48442932&amp;how=up&amp;goto=news" id="up_48442932"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://sbbresale.ch/">Buy a train, bridge or tracks from the Swiss Railway</a><span class="sitebit comhead"> (<a href="from?site=sbbresale.ch"><span class="sitestr">sbbresale.ch</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48477551"><td align="right" class="title" valign="top"><span class="rank">11.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48477551&amp;how=up&amp;goto=news" id="up_48477551"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://www.bls.gov/news.release/cpi.nr0.htm">US Consumer Price Index up 4.2%</a><span class="sitebit comhead"> (<a href="from?site=bls.gov"><span class="sitestr">bls.gov</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48445702"><td align="right" class="title" valign="top"><span class="rank">12.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48445702&amp;how=up&amp;goto=news" id="up_48445702"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://aibodh.com/posts/async-rust-chapter-1-hands-on-intro-to-async-rust/">Who Runs Your Rust Future? Hands-On Intro to Async Rust</a><span class="sitebit comhead"> (<a href="from?site=aibodh.com"><span class="sitestr">aibodh.com</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48478285"><td align="right" class="title" valign="top"><span class="rank">13.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48478285&amp;how=up&amp;goto=news" id="up_48478285"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://www.gutenberg.org/files/27462/27462-h/27462-h.htm" rel="nofollow">The Last Evolution, by John W Campbell Jr. (1932)</a><span class="sitebit comhead"> (<a href="from?site=gutenberg.org"><span class="sitestr">gutenberg.org</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48447378"><td align="right" class="title" valign="top"><span class="rank">14.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48447378&amp;how=up&amp;goto=news" id="up_48447378"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://www.theguardian.com/science/2026/jun/02/journey-into-spain-palaeolithic-cave-paintings-altamira">'They take you out of life, out of time': a journey into Spain's cave paintings</a><span class="sitebit comhead"> (<a href="from?site=theguardian.com"><span class="sitestr">theguardian.com</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48470578"><td align="right" class="title" valign="top"><span class="rank">15.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48470578&amp;how=up&amp;goto=news" id="up_48470578"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://www.inverse.com/input/gaming/the-dirty-secret-that-makes-speedrunning-on-spongebob-a-lot-faster">Smudging the game disc to make speedrunning 'SpongeBob' faster</a><span class="sitebit comhead"> (<a href="from?site=inverse.com"><span class="sitestr">inverse.com</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48473166"><td align="right" class="title" valign="top"><span class="rank">16.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48473166&amp;how=up&amp;goto=news" id="up_48473166"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="item?id=48473166">AWS Bedrock to require sharing data with Anthropic for Mythos and future models</a></span></td></tr>,
 <tr class="athing submission" id="48443644"><td align="right" class="title" valign="top"><span class="rank">17.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48443644&amp;how=up&amp;goto=news" id="up_48443644"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://paperswithcode.co/">Reviving Papers with Code</a><span class="sitebit comhead"> (<a href="from?site=paperswithcode.co"><span class="sitestr">paperswithcode.co</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48475871"><td align="right" class="title" valign="top"><span class="rank">18.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48475871&amp;how=up&amp;goto=news" id="up_48475871"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="item?id=48475871">Ask HN: Are most corporate SWE jobs performative?</a></span></td></tr>,
 <tr class="athing submission" id="48451789"><td align="right" class="title" valign="top"><span class="rank">19.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48451789&amp;how=up&amp;goto=news" id="up_48451789"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://steveblank.com/2026/06/08/g-for-defense-stanford-2026-lessons-learned-presentations/">Hacking for Defense Stanford 2026 – Lessons Learned Presentations</a><span class="sitebit comhead"> (<a href="from?site=steveblank.com"><span class="sitestr">steveblank.com</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48477589"><td align="right" class="title" valign="top"><span class="rank">20.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48477589&amp;how=up&amp;goto=news" id="up_48477589"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://p2claw.com/blog/2026-06-09-the-ipad-was-on-tailscale/" rel="nofollow">The iPad was on Tailscale: a WebRTC debugging story</a><span class="sitebit comhead"> (<a href="from?site=p2claw.com"><span class="sitestr">p2claw.com</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48467705"><td align="right" class="title" valign="top"><span class="rank">21.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48467705&amp;how=up&amp;goto=news" id="up_48467705"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://github.blog/changelog/2026-06-09-upcoming-breaking-changes-for-npm-v12/">Upcoming breaking changes for npm v12</a><span class="sitebit comhead"> (<a href="from?site=github.blog"><span class="sitestr">github.blog</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48475938"><td align="right" class="title" valign="top"><span class="rank">22.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48475938&amp;how=up&amp;goto=news" id="up_48475938"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://danq.me/2026/06/09/fn-keys/">I Hate (Most) Keyboard 'Fn' Keys</a><span class="sitebit comhead"> (<a href="from?site=danq.me"><span class="sitestr">danq.me</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48427324"><td align="right" class="title" valign="top"><span class="rank">23.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48427324&amp;how=up&amp;goto=news" id="up_48427324"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://kennethreitz.org/essays/2026-06-05-a_server_called_mercury" rel="nofollow">A Server Called Mercury</a><span class="sitebit comhead"> (<a href="from?site=kennethreitz.org"><span class="sitestr">kennethreitz.org</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48433525"><td align="right" class="title" valign="top"><span class="rank">24.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48433525&amp;how=up&amp;goto=news" id="up_48433525"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://newatlas.com/engineering/magnetoelectric-antennas-submarine-robots-communications/">Magnetoelectric antennas could transform how underwater robots talk</a><span class="sitebit comhead"> (<a href="from?site=newatlas.com"><span class="sitestr">newatlas.com</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48471970"><td align="right" class="title" valign="top"><span class="rank">25.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48471970&amp;how=up&amp;goto=news" id="up_48471970"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://www.neowin.net/news/google-chrome-is-killing-all-ublock-origin-bypasses-microsoft-edge-opera-to-follow/">Chrome is looking to permanently drop MV2 extension</a><span class="sitebit comhead"> (<a href="from?site=neowin.net"><span class="sitestr">neowin.net</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48476474"><td align="right" class="title" valign="top"><span class="rank">26.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48476474&amp;how=up&amp;goto=news" id="up_48476474"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://twitter.com/NikoMcCarty/status/2064686557400100884">Notes on DeepSeek</a><span class="sitebit comhead"> (<a href="from?site=twitter.com/nikomccarty"><span class="sitestr">twitter.com/nikomccarty</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48470248"><td align="right" class="title" valign="top"><span class="rank">27.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48470248&amp;how=up&amp;goto=news" id="up_48470248"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://the-decoder.com/landmark-german-ruling-declares-googles-ai-overviews-are-googles-own-words-and-makes-it-liable-for-false-answers/">German ruling declares Google liable for false answers in AI Overviews</a><span class="sitebit comhead"> (<a href="from?site=the-decoder.com"><span class="sitestr">the-decoder.com</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48468766"><td align="right" class="title" valign="top"><span class="rank">28.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48468766&amp;how=up&amp;goto=news" id="up_48468766"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://blog.oscars.dev/posts/rip-software-hackathons-long-live-the-hardware-hackathon/">RIP software hackathons. Long live the hardware hackathon</a><span class="sitebit comhead"> (<a href="from?site=oscars.dev"><span class="sitestr">oscars.dev</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48470581"><td align="right" class="title" valign="top"><span class="rank">29.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48470581&amp;how=up&amp;goto=news" id="up_48470581"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://twitter.com/RichardSSutton/status/2061216087744946656">Rich Sutton on AI creativity and discovery</a><span class="sitebit comhead"> (<a href="from?site=twitter.com/richardssutton"><span class="sitestr">twitter.com/richardssutton</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48468370"><td align="right" class="title" valign="top"><span class="rank">30.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48468370&amp;how=up&amp;goto=news" id="up_48468370"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://forestwalk.ai/blog/surprise-blacksmith-costs/">Surprise, pay $1000</a><span class="sitebit comhead"> (<a href="from?site=forestwalk.ai"><span class="sitestr">forestwalk.ai</span></a>)</span></span></td></tr>]

In [ ]:
soup.find_all("tr" , class_=["athing", "submission"])

In [51]:
url = item.find("span" , class_ = 'sitestr')

In [53]:
url.text

'cityam.com'

In [ ]:
l = []
for item in allcontent:
    rank = item.find("span" , class_='rank').text
    title = item.find("span" , class_='titleline').find("a").text
    url = item.find("span" , class_ = 'sitestr')
    
    dic = { 
        "Rank" : rank,
        "Title" : title,
        "URL" : url
    }
    l.append(dic)

In [50]:
df1 = pd.DataFrame(l)
df1

,Rank,Title,URL
0,781.,American Fork PD posts and removes unredacted ...,[reddit.com]
1,782.,'Bear-Repelling Poles' Attracting Attention; D...,[yomiuri.co.jp]
2,783.,Parsing XML EXIF from .avif files (plus a rant),[sheep.horse]
3,784.,Python JIT project was asked to pause development,[python.org]
4,785.,NSA using Anthropic's Mythos for cyber attacks,[ft.com]
5,786.,Show HN: FFmpeg WebCLI – Full FFmpeg in Browse...,[github.com/tejaswigowda]
6,787.,Show HN: Netlora diagnose bufferbloat and why ...,[getnetlora.com]
7,788.,Internet Age-Gates Are a Growing Global Threat,[eff.org]
8,789.,Meta Silently Added Face-Recognition for Its S...,[wired.com]
9,790.,"Alan Kay on ""Should web browsers have stuck to...",[donhopkins.medium.com]
10,791.,"Palantir to manage UK firearms, explosives, an...",[theregister.com]
11,792.,Extreme heat will double US hospitalizations b...,[theguardian.com]
12,793.,"No Model Will Save Us: Pope Leo, the Miserosta...",[wmbriggs.com]
13,794.,Floppy Disk patent was granted today in 1972 –...,[tomshardware.com]
14,795.,The architecture of the internet creates risks...,[science.org]
15,796.,Realtime regression in non-English production ...,[community.openai.com]
16,797.,Ask HN: How to get my contact info off US poli...,None
17,798.,'World-first' vaccine designed by artificial i...,[bbc.com]
18,799.,Some concerns about Ladybird's (Browser) bylaws,[tuananh.net]
19,800.,Show HN: Concord – Discord in Terminal,[github.com/chojs23]
20,801.,People with cancer / HIV could lose Medicaid u...,[npr.org]
21,802.,Yon – a topos-oriented language with a content...,[yon-lang.org]
22,803.,"Lambda isn't leaking memory, your metrics are ...",[taktile.com]
23,804.,"The mayor of Shelbyville, IN says only 'shitty...",[theverge.com]
24,805.,Optimizing for Text-Mode Browsers,[schemescape.com]
25,806.,"Police remove biabetes researcher, other exper...",[seattletimes.com]
26,807.,"Let us filter AI slop, you cowards",[theverge.com]
27,808.,Let's celebrate work that is 100% human-made,[human-made.work]
28,809.,Tests suggest Russian satellites can jam GPS o...,[arstechnica.com]
29,810.,There should have been an op-ed here but you f...,[cityam.com]

In [84]:
allother = soup.find_all("span",class_='subline')

In [100]:
m = []
for item in allother:
    points = item.find("span").text
    author = item.find("a").text
    comments = item.find_all("a")[-1].text

    dic = {
        "Points" : points,
        "Author" : author,
        "Comments" : comments
    }

    m.append(dic)

In [102]:
df2 = pd.DataFrame(m)
df2

        Points           Author      Comments
0    60 points       gainsurier   10 comments
1   213 points          lizhang   42 comments
2   145 points          dariubs   67 comments
3    65 points         fkilaiwi   15 comments
4   242 points    1vuio0pswjnm7  212 comments
5   234 points         yu3zhou4   76 comments
6   259 points           mhrmsn   56 comments
7    36 points       emschwartz   31 comments
8    84 points            Tomte   19 comments
9   609 points             igmn  307 comments
10   32 points          mmarian   13 comments
11  255 points  882542F3884314B  100 comments
12   25 points           greedo     1 comment
13   22 points      dredmorbius   10 comments
14  799 points         gavinray  364 comments
15   89 points    marysminefnuf   23 comments
16   48 points          signa11   10 comments
17  251 points       vthommeret  159 comments
18  272 points   DevarshRanpara   60 comments
19   68 points     surprisetalk    5 comments
20  112 points        nicwilson   30 comments
21  123 points          prestoj   10 comments
22   15 points      billtarbell    9 comments
23  281 points         herbertl  175 comments
24   52 points            spwa4   47 comments
25  247 points            gmays   43 comments
26   12 points          mooreds    3 comments
27  302 points           bkazez  120 comments
28   60 points    markusheimerl   13 comments
29   14 points              luu    6 comments

In [107]:
df = pd.concat([df1,df2] , axis = 1)
df

,Rank,Title,URL,Points,Author,Comments
0,1.,MiMo-v2.5-Pro-UltraSpeed: 1T model with 1000 t...,xiaomi.com,60 points,gainsurier,10 comments
1,2.,Show HN: Performative-UI – a react component l...,vorpus.github.io,213 points,lizhang,42 comments
2,3.,Zig by Example,github.com/boringcollege,145 points,dariubs,67 comments
3,4.,Launch HN: Intuned (YC S22) – Build and run re...,intunedhq.com,65 points,fkilaiwi,15 comments
4,5.,"Anti-social: It's fads, not friends, which now...",bbc.com,242 points,1vuio0pswjnm7,212 comments
5,6.,The Cypherpunk Library,cypherpunkbooks.com,234 points,yu3zhou4,76 comments
6,7.,How much of Thermo Fisher's antibody data has ...,reeserichardson.blog,259 points,mhrmsn,56 comments
7,8.,Life is too short for a slow terminal,mijndertstuij.nl,36 points,emschwartz,31 comments
8,9.,Zig Structs of Arrays (2024),andreashohmann.com,84 points,Tomte,19 comments
9,10.,Dopamine Fracking,igerman.cc,609 points,igmn,307 comments
10,11.,"Italy's Bending Spoons, Owner of AOL and Vimeo...",reuters.com,32 points,mmarian,13 comments
11,12.,"1k Data Breaches Later, the Disclosure Lag Is ...",troyhunt.com,255 points,882542F3884314B,100 comments
12,13.,A Farmer Donated Land to Turn into a Park. The...,404media.co,25 points,greedo,1 comment
13,14.,I replaced Spotify with a homemade FM radio st...,reddit.com,22 points,dredmorbius,10 comments
14,15.,"Building from zero after addiction, prison, an...",gavinray97.github.io,799 points,gavinray,364 comments
15,16.,Spherical Voronoi Diagram,jasondavies.com,89 points,marysminefnuf,23 comments
16,17.,Config Files That Run Code: Supply Chain Secur...,safedep.io,48 points,signa11,10 comments
17,18.,APC–2 – A professional record cutter for produ...,teenage.engineering,251 points,vthommeret,159 comments
18,19.,The Smallest Brain You Can Build: A Perceptron...,ranpara.net,272 points,DevarshRanpara,60 comments
19,20.,A Family Project (2022),bittersoutherner.com,68 points,surprisetalk,5 comments
20,21.,Richard Scolyer Has Died,bbc.com,112 points,nicwilson,30 comments
21,22.,Playing with Vision Embeddings,prestonbjensen.com,123 points,prestoj,10 comments
22,23.,SoulsOnly.tff – A font for humans not AI and k...,github.com/convictional,15 points,billtarbell,9 comments
23,24.,Making peace with your unlived dreams (2023),nik.art,281 points,herbertl,175 comments
24,25.,Nvidia partners with LG robotics to build huma...,nvidia.com,52 points,spwa4,47 comments
25,26.,New drug 'functionally cures' many hepatitis B...,science.org,247 points,gmays,43 comments
26,27.,Amazon Cognito now supports multi-Region repli...,amazon.com,12 points,mooreds,3 comments
27,28.,Show HN: I Derived a Pancake,absurdlyoptimized.com,302 points,bkazez,120 comments
28,29.,Tiny hackable CUDA language model implementation,github.com/markusheimerl,60 points,markusheimerl,13 comments
29,30.,A modular impact diverting mechanism for footb...,sfu.ca,14 points,luu,6 comments

In [110]:
df['Rank'] = df['Rank'].str.replace('.' , '')

In [116]:
df['Points'] = df['Points'].str[:-6]

In [120]:
df['Comments'] = df['Comments'].str[:-8].str.strip()

# Checking Data is right or not

In [121]:
df

,Rank,Title,URL,Points,Author,Comments
0,1,MiMo-v2.5-Pro-UltraSpeed: 1T model with 1000 t...,xiaomi.com,60,gainsurier,10
1,2,Show HN: Performative-UI – a react component l...,vorpus.github.io,213,lizhang,42
2,3,Zig by Example,github.com/boringcollege,145,dariubs,67
3,4,Launch HN: Intuned (YC S22) – Build and run re...,intunedhq.com,65,fkilaiwi,15
4,5,"Anti-social: It's fads, not friends, which now...",bbc.com,242,1vuio0pswjnm7,212
5,6,The Cypherpunk Library,cypherpunkbooks.com,234,yu3zhou4,76
6,7,How much of Thermo Fisher's antibody data has ...,reeserichardson.blog,259,mhrmsn,56
7,8,Life is too short for a slow terminal,mijndertstuij.nl,36,emschwartz,31
8,9,Zig Structs of Arrays (2024),andreashohmann.com,84,Tomte,19
9,10,Dopamine Fracking,igerman.cc,609,igmn,307
10,11,"Italy's Bending Spoons, Owner of AOL and Vimeo...",reuters.com,32,mmarian,13
11,12,"1k Data Breaches Later, the Disclosure Lag Is ...",troyhunt.com,255,882542F3884314B,100
12,13,A Farmer Donated Land to Turn into a Park. The...,404media.co,25,greedo,1
13,14,I replaced Spotify with a homemade FM radio st...,reddit.com,22,dredmorbius,10
14,15,"Building from zero after addiction, prison, an...",gavinray97.github.io,799,gavinray,364
15,16,Spherical Voronoi Diagram,jasondavies.com,89,marysminefnuf,23
16,17,Config Files That Run Code: Supply Chain Secur...,safedep.io,48,signa11,10
17,18,APC–2 – A professional record cutter for produ...,teenage.engineering,251,vthommeret,159
18,19,The Smallest Brain You Can Build: A Perceptron...,ranpara.net,272,DevarshRanpara,60
19,20,A Family Project (2022),bittersoutherner.com,68,surprisetalk,5
20,21,Richard Scolyer Has Died,bbc.com,112,nicwilson,30
21,22,Playing with Vision Embeddings,prestonbjensen.com,123,prestoj,10
22,23,SoulsOnly.tff – A font for humans not AI and k...,github.com/convictional,15,billtarbell,9
23,24,Making peace with your unlived dreams (2023),nik.art,281,herbertl,175
24,25,Nvidia partners with LG robotics to build huma...,nvidia.com,52,spwa4,47
25,26,New drug 'functionally cures' many hepatitis B...,science.org,247,gmays,43
26,27,Amazon Cognito now supports multi-Region repli...,amazon.com,12,mooreds,3
27,28,Show HN: I Derived a Pancake,absurdlyoptimized.com,302,bkazez,120
28,29,Tiny hackable CUDA language model implementation,github.com/markusheimerl,60,markusheimerl,13
29,30,A modular impact diverting mechanism for footb...,sfu.ca,14,luu,6

In [125]:
df['Points'] = df['Points'].str.strip()

In [132]:
df[df['Points'] == '89']['Author'].values.item()

'marysminefnuf'

In [135]:
df['Comments'] = df['Comments'].str.strip()

In [137]:
df['Comments'] = df['Comments'].astype('int')

In [139]:
df['Comments'].mean().item()

67.86666666666666

In [143]:
df['Points'] = df['Points'].astype('int')

In [151]:
df.sort_values('Points',ascending = False).head()['Title'].values[:]

array(['Building from zero after addiction, prison, and a felony',
       'Dopamine Fracking', 'Show HN: I Derived a Pancake',
       'Making peace with your unlived dreams (2023)',
       'The Smallest Brain You Can Build: A Perceptron in Python'],
      dtype=object)

# Getting all Data

In [57]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

page_url = "https://news.ycombinator.com/"  # renamed from url
headers = {"User-Agent": "Mozilla/5.0"}
new_df = pd.DataFrame()
page_count = 0

while True:
    response = requests.get(page_url, headers=headers)
    soup = BeautifulSoup(response.text, "html.parser")
    
    allcontent = soup.select("tr.athing.submission")
    l = []
    for item in allcontent:
        rank = item.find("span", class_='rank').text
        title = item.find("span", class_='titleline').find("a").text
        link = item.find("span", class_='titleline').find("a")["href"]  # actual article link
        site = item.find("span", class_='sitestr').text if item.find("span", class_='sitestr') else "N/A"  # None fix
        
        l.append({"Rank": rank, "Title": title, "Link": link, "Site": site})

    df1 = pd.DataFrame(l)

    allother = soup.find_all("span", class_='subline')
    m = []
    for item in allother:
        points = item.find("span").text
        author = item.find("a").text
        comments = item.find_all("a")[-1].text
        m.append({"Points": points, "Author": author, "Comments": comments})

    df2 = pd.DataFrame(m)

    df = pd.concat([df1, df2], axis=1)

    df['Rank'] = df['Rank'].str.replace('.', '')
    df['Points'] = df['Points'].str[:-6]
    df['Comments'] = df['Comments'].str[:-8].str.strip()

    new_df = pd.concat([new_df, df], ignore_index=True)

    next_button = soup.find("a", class_="morelink")
    if next_button:
        page_url = "https://news.ycombinator.com/" + next_button["href"]  # uses renamed variable
    else:
        break

    page_count += 1
    time.sleep(2)

In [58]:
new_df

,Rank,Title,Link,Site,Points,Author,Comments
0,1,Building an HTML-first site doubled our users ...,https://mohkohn.co.uk/writing/html-first/,mohkohn.co.uk,611,edent,271
1,2,AMA: I'm Eric Ries (The Lean Startup) & Author...,item?id=48477135,N/A,174,eries,91
2,3,PgDog is funded and coming to a database near you,https://pgdog.dev/blog/our-funding-announcement,pgdog.dev,166,levkk,90
3,4,Apache Burr: Build reliable AI agents and appl...,https://burr.apache.org/,apache.org,66,anhldbk,32
4,5,GitHub Authentication issues related to API re...,https://www.githubstatus.com/incidents/fcj3088...,githubstatus.com,53,Multicomp,12
...,...,...,...,...,...,...,...
805,806,Yon – a topos-oriented language with a content...,https://yon-lang.org/,yon-lang.org,47,amenn,78
806,807,"Lambda isn't leaking memory, your metrics are ...",https://engineering.taktile.com/blog/onnx-memo...,taktile.com,18,tlarkworthy,5
807,808,"The mayor of Shelbyville, IN says only 'shitty...",https://www.theverge.com/ai-artificial-intelli...,theverge.com,23,timpera,3
808,809,Optimizing for Text-Mode Browsers,https://log.schemescape.com/posts/web-developm...,schemescape.com,7,zdw,2
809,810,"Police remove biabetes researcher, other exper...",https://www.seattletimes.com/seattle-news/heal...,seattletimes.com,20,anigbrowl,15

0     NaN
1     NaN
2     NaN
3     NaN
4     NaN
       ..
805   NaN
806   NaN
807   NaN
808   NaN
809   NaN
Name: URL, Length: 810, dtype: float64