# Naukri Scraper — Simple Version
Only uses what we learned. No advanced stuff.

In [6]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from webdriver_manager.chrome import ChromeDriverManager
from bs4 import BeautifulSoup
import pandas as pd
import time

In [7]:
# Concept 1 — Setup (exactly as taught)
def get_driver():
    return webdriver.Chrome(service=Service(ChromeDriverManager().install()))

In [8]:
driver = get_driver()
driver.implicitly_wait(10)   # Concept 6 — implicit wait

driver.get("https://www.naukri.com/data-analyst-jobs-in-all-india")
time.sleep(4)
print("Title:", driver.title)

Title: Data Analyst Jobs In All India - 26637 Data Analyst Job Vacancies In All India - Naukri.com

In [9]:
# Print ONE card HTML so you can see the actual structure
# This helps us find correct selectors for salary / rating / reviews
html = driver.page_source
soup = BeautifulSoup(html, "html.parser")
cards = soup.select("div.srp-jobtuple-wrapper")
print("Cards found:", len(cards))

# Print first card HTML to inspect structure
print("\n--- FIRST CARD HTML ---")
print(cards[0].prettify()[:3000])   # .prettify() — Day 2 concept

Cards found: 20

--- FIRST CARD HTML ---
<div class="srp-jobtuple-wrapper" data-job-id="140526016202">
 <div class="cust-job-tuple layout-wrapper lay-2 sjw__tuple">
  <div class="row1">
   <h2>
    <a class="title" href="https://www.naukri.com/job-listings-data-analyst-immediate-joiners-preferred-capita-pune-mumbai-all-areas-1-to-5-years-140526016202" rel="noopener noreferrer" target="_blank" title="Data Analyst - (Immediate Joiners preferred)">
     Data Analyst - (Immediate Joiners preferred)
    </a>
   </h2>
   <span class="imagewrap">
    <img class="logoImage" loading="lazy" src="https://img.naukimg.com/logo_images/groups/v1/599384.gif"/>
   </span>
  </div>
  <div class="row2">
   <span class="comp-dtls-wrap">
    <a class="comp-name mw-25" href="https://www.naukri.com/capita-jobs-careers-143636" target="_blank" title="Capita">
     Capita
    </a>
    <a class="rating" href="https://www.ambitionbox.com/reviews/capita-reviews?utm_campaign=srp_ratings&amp;utm_medium=desktop&amp;utm_source=naukri" target="_blank" title="Powered by Ambition Box">
     <span class="ni-job-tuple-icon ni-job-tuple-icon-ot_star star">
     </span>
     <span class="main-2">
      3.5
     </span>
     <span class="ni-job-tuple-icon ni-job-tuple-icon-ot_star">
     </span>
    </a>
    <a class="review ver-line" href="https://www.ambitionbox.com/reviews/capita-reviews?utm_campaign=srp_ratings&amp;utm_medium=desktop&amp;utm_source=naukri" target="_blank" title="Powered by Ambition Box">
     2694  Reviews
    </a>
   </span>
  </div>
  <div class="row3">
   <div class="job-details">
    <span class="exp-wrap">
     <span class="ni-job-tuple-icon ni-job-tuple-icon-srp-experience exp">
      <span class="expwdth" title="1-5 Yrs ">
       1-5 Yrs
      </span>
     </span>
    </span>
    <span class="loc-wrap ver-line">
     <span class="ni-job-tuple-icon ni-job-tuple-icon-srp-location loc">
      <span class="locWdth" title="Hybrid - Pune, Mumbai (All Areas) ">
       Hybrid - Pune, Mumbai (All Areas)
      </span>
     </span>
    </span>
   </div>
  </div>
  <div class="row4">
   <span class="job-desc ni-job-tuple-icon ni-job-tuple-icon-srp-description">
    Shift Timings: 1pm - 10pm (UK Shift). Preferred candidate profile : .
   </span>
  </div>
  <div class="row5">
   <ul class="tags-gt">
    <li class="dot-gt tag-li">
     Power Bi
    </li>
    <li class="dot-gt tag-li">
     Advanced Excel
    </li>
    <li class="dot-gt tag-li">
     Machine Learning
    </li>
    <li class="dot-gt tag-li">
     Python
    </li>
    <li class="dot-gt tag-li">
     R
    </li>
    <li class="dot-gt tag-li">
     Data Visualization
    </li>
    <li class="dot-gt tag-li">
     Tableau
    </li>
    <li class="dot-gt tag-li">
     Data analysis
    </li>
   </ul>
  </div>
  <div class="row6">
   <span class="job-post-day">
    1 week ago
   </span>
   <span class="ni-job-tuple-icon ni-job-tuple-icon-srpSaveUnfilled un-saved save-job-tag">
    save
   </span>
  </div>
 </div>
</div>

In [10]:
MAX_PAGES = 220  # Change to 220 for full scrape

all_data = []   # one list outside loop — Hacker News pattern

for page in range(1, MAX_PAGES + 1):
    
    # URL pagination — same as books.toscrape
    url = f"https://www.naukri.com/data-analyst-jobs-in-all-india-{page}"
    driver.get(url)
    time.sleep(5)   # time.sleep — delays between requests
    
    # Selenium + BeautifulSoup combo (what we learned)
    html = driver.page_source
    soup = BeautifulSoup(html, "html.parser")
    
    cards = soup.select("div.srp-jobtuple-wrapper")   # soup.select — Day 2
    
    if not cards:
        print(f"Page {page}: no cards — stopping")
        break
    
    for card in cards:
        
        # --- Title ---
        title_tag = card.select_one("a.title")
        title     = title_tag.text.strip() if title_tag else "N/A"
        link      = title_tag["href"]      if title_tag else "N/A"
        
        # --- Company ---
        company_tag = card.select_one("a.comp-name")
        company     = company_tag.text.strip() if company_tag else "N/A"
        
        # --- Experience ---
        exp_tag    = card.select_one(".expwdth")
        experience = exp_tag.text.strip() if exp_tag else "N/A"
        
        # --- Location ---
        loc_tag  = card.select_one(".locWdth")
        location = loc_tag.text.strip() if loc_tag else "N/A"
        
        # --- Salary ---
        # Try multiple selectors because Naukri uses different ones
        sal_tag = card.select_one(".sal-wrap span[title]")   # has title attribute
        if not sal_tag:
            sal_tag = card.select_one(".sal-wrap span")       # any span inside sal-wrap
        if not sal_tag:
            sal_tag = card.select_one(".sal-wrap")            # the wrap itself
        if sal_tag:
            salary = sal_tag.get("title") or sal_tag.text.strip()
        else:
            salary = "Not Disclosed"
        
        # --- Rating ---
        # Try class names that Naukri uses for ratings
        rat_tag = card.select_one(".ambRating")
        if not rat_tag:
            rat_tag = card.select_one(".rating")
        if not rat_tag:
            # find any span whose class contains "rating"
            rat_tag = card.find("span", class_=lambda c: c and "ating" in c)
        rating = rat_tag.text.strip() if rat_tag else "N/A"
        
        # --- Reviews ---
        rev_tag = card.select_one(".review")
        if not rev_tag:
            rev_tag = card.find("span", class_=lambda c: c and "eview" in c)
        reviews = rev_tag.text.strip() if rev_tag else "N/A"
        
        # --- Posted date ---
        date_tag = card.select_one(".job-post-day")
        posted   = date_tag.text.strip() if date_tag else "N/A"
        
        # list of dicts — Day 1 pattern
        all_data.append({
            "Title"      : title,
            "Company"    : company,
            "Experience" : experience,
            "Salary"     : salary,
            "Location"   : location,
            "Rating"     : rating,
            "Reviews"    : reviews,
            "Posted"     : posted,
            "Link"       : link
        })
    
    print(f"Page {page} — {len(cards)} jobs | Total: {len(all_data)}")

driver.quit()   # always close
print(f"Done. Total jobs: {len(all_data)}")

Page 1 — 20 jobs | Total: 20
Page 2 — 20 jobs | Total: 40
Page 3 — 20 jobs | Total: 60
Page 4 — 20 jobs | Total: 80
Page 5 — 20 jobs | Total: 100
Page 6 — 20 jobs | Total: 120
Page 7 — 20 jobs | Total: 140
Page 8 — 20 jobs | Total: 160
Page 9 — 20 jobs | Total: 180
Page 10 — 20 jobs | Total: 200
Page 11 — 20 jobs | Total: 220
Page 12 — 19 jobs | Total: 239
Page 13 — 20 jobs | Total: 259
Page 14 — 20 jobs | Total: 279
Page 15 — 20 jobs | Total: 299
Page 16 — 20 jobs | Total: 319
Page 17 — 20 jobs | Total: 339
Page 18 — 20 jobs | Total: 359
Page 19 — 20 jobs | Total: 379
Page 20 — 20 jobs | Total: 399
Page 21 — 20 jobs | Total: 419
Page 22 — 20 jobs | Total: 439
Page 23 — 20 jobs | Total: 459
Page 24 — 20 jobs | Total: 479
Page 25 — 20 jobs | Total: 499
Page 26 — 20 jobs | Total: 519
Page 27 — 20 jobs | Total: 539
Page 28 — 20 jobs | Total: 559
Page 29 — 20 jobs | Total: 579
Page 30 — 20 jobs | Total: 599
Page 31 — 20 jobs | Total: 619
Page 32 — 20 jobs | Total: 639
Page 33 — 20 jobs | Total: 659
Page 34 — 20 jobs | Total: 679
Page 35 — 20 jobs | Total: 699
Page 36 — 20 jobs | Total: 719
Page 37 — 20 jobs | Total: 739
Page 38 — 20 jobs | Total: 759
Page 39 — 20 jobs | Total: 779
Page 40 — 20 jobs | Total: 799
Page 41 — 20 jobs | Total: 819
Page 42 — 20 jobs | Total: 839
Page 43 — 20 jobs | Total: 859
Page 44 — 20 jobs | Total: 879
Page 45 — 20 jobs | Total: 899
Page 46 — 20 jobs | Total: 919
Page 47 — 20 jobs | Total: 939
Page 48 — 20 jobs | Total: 959
Page 49 — 20 jobs | Total: 979
Page 50 — 20 jobs | Total: 999
Page 51 — 20 jobs | Total: 1019
Page 52 — 20 jobs | Total: 1039
Page 53 — 20 jobs | Total: 1059
Page 54 — 20 jobs | Total: 1079
Page 55 — 20 jobs | Total: 1099
Page 56 — 20 jobs | Total: 1119
Page 57 — 20 jobs | Total: 1139
Page 58 — 20 jobs | Total: 1159
Page 59 — 20 jobs | Total: 1179
Page 60 — 20 jobs | Total: 1199
Page 61 — 20 jobs | Total: 1219
Page 62 — 20 jobs | Total: 1239
Page 63 — 20 jobs | Total: 1259
Page 64 — 20 jobs | Total: 1279
Page 65 — 20 jobs | Total: 1299
Page 66 — 20 jobs | Total: 1319
Page 67 — 20 jobs | Total: 1339
Page 68 — 20 jobs | Total: 1359
Page 69 — 20 jobs | Total: 1379
Page 70 — 20 jobs | Total: 1399
Page 71 — 20 jobs | Total: 1419
Page 72 — 20 jobs | Total: 1439
Page 73 — 20 jobs | Total: 1459
Page 74 — 20 jobs | Total: 1479
Page 75 — 20 jobs | Total: 1499
Page 76 — 20 jobs | Total: 1519
Page 77 — 20 jobs | Total: 1539
Page 78 — 20 jobs | Total: 1559
Page 79 — 20 jobs | Total: 1579
Page 80 — 20 jobs | Total: 1599
Page 81 — 20 jobs | Total: 1619
Page 82 — 20 jobs | Total: 1639
Page 83 — 20 jobs | Total: 1659
Page 84 — 20 jobs | Total: 1679
Page 85 — 20 jobs | Total: 1699
Page 86 — 20 jobs | Total: 1719
Page 87 — 20 jobs | Total: 1739
Page 88 — 20 jobs | Total: 1759
Page 89 — 20 jobs | Total: 1779
Page 90 — 20 jobs | Total: 1799
Page 91 — 20 jobs | Total: 1819
Page 92 — 20 jobs | Total: 1839
Page 93 — 20 jobs | Total: 1859
Page 94 — 20 jobs | Total: 1879
Page 95 — 20 jobs | Total: 1899
Page 96 — 20 jobs | Total: 1919
Page 97 — 20 jobs | Total: 1939
Page 98 — 20 jobs | Total: 1959
Page 99 — 20 jobs | Total: 1979
Page 100 — 20 jobs | Total: 1999
Page 101 — 20 jobs | Total: 2019
Page 102 — 20 jobs | Total: 2039
Page 103 — 20 jobs | Total: 2059
Page 104 — 20 jobs | Total: 2079
Page 105 — 20 jobs | Total: 2099
Page 106 — 20 jobs | Total: 2119
Page 107 — 20 jobs | Total: 2139
Page 108 — 20 jobs | Total: 2159
Page 109 — 20 jobs | Total: 2179
Page 110 — 20 jobs | Total: 2199
Page 111 — 20 jobs | Total: 2219
Page 112 — 20 jobs | Total: 2239
Page 113 — 20 jobs | Total: 2259
Page 114 — 20 jobs | Total: 2279
Page 115 — 20 jobs | Total: 2299
Page 116 — 20 jobs | Total: 2319
Page 117 — 20 jobs | Total: 2339
Page 118 — 20 jobs | Total: 2359
Page 119 — 20 jobs | Total: 2379
Page 120 — 20 jobs | Total: 2399
Page 121 — 20 jobs | Total: 2419
Page 122 — 20 jobs | Total: 2439
Page 123 — 20 jobs | Total: 2459
Page 124 — 20 jobs | Total: 2479
Page 125 — 20 jobs | Total: 2499
Page 126 — 20 jobs | Total: 2519
Page 127 — 20 jobs | Total: 2539
Page 128 — 20 jobs | Total: 2559
Page 129 — 20 jobs | Total: 2579
Page 130 — 20 jobs | Total: 2599
Page 131 — 20 jobs | Total: 2619
Page 132 — 20 jobs | Total: 2639
Page 133 — 20 jobs | Total: 2659
Page 134 — 20 jobs | Total: 2679
Page 135 — 20 jobs | Total: 2699
Page 136 — 20 jobs | Total: 2719
Page 137 — 20 jobs | Total: 2739
Page 138 — 20 jobs | Total: 2759
Page 139 — 20 jobs | Total: 2779
Page 140 — 20 jobs | Total: 2799
Page 141 — 20 jobs | Total: 2819
Page 142 — 20 jobs | Total: 2839
Page 143 — 20 jobs | Total: 2859
Page 144 — 19 jobs | Total: 2878
Page 145 — 20 jobs | Total: 2898
Page 146 — 20 jobs | Total: 2918
Page 147 — 20 jobs | Total: 2938
Page 148 — 20 jobs | Total: 2958
Page 149 — 20 jobs | Total: 2978
Page 150 — 20 jobs | Total: 2998
Page 151 — 20 jobs | Total: 3018
Page 152 — 20 jobs | Total: 3038
Page 153 — 20 jobs | Total: 3058
Page 154 — 20 jobs | Total: 3078
Page 155 — 20 jobs | Total: 3098
Page 156 — 20 jobs | Total: 3118
Page 157 — 20 jobs | Total: 3138
Page 158 — 20 jobs | Total: 3158
Page 159 — 20 jobs | Total: 3178
Page 160 — 20 jobs | Total: 3198
Page 161 — 20 jobs | Total: 3218
Page 162 — 20 jobs | Total: 3238
Page 163 — 20 jobs | Total: 3258
Page 164 — 20 jobs | Total: 3278
Page 165 — 20 jobs | Total: 3298
Page 166 — 20 jobs | Total: 3318
Page 167 — 20 jobs | Total: 3338
Page 168 — 20 jobs | Total: 3358
Page 169 — 20 jobs | Total: 3378
Page 170 — 20 jobs | Total: 3398
Page 171 — 20 jobs | Total: 3418
Page 172 — 20 jobs | Total: 3438
Page 173 — 20 jobs | Total: 3458
Page 174 — 20 jobs | Total: 3478
Page 175 — 20 jobs | Total: 3498
Page 176 — 20 jobs | Total: 3518
Page 177 — 20 jobs | Total: 3538
Page 178 — 20 jobs | Total: 3558
Page 179 — 20 jobs | Total: 3578
Page 180 — 20 jobs | Total: 3598
Page 181 — 20 jobs | Total: 3618
Page 182 — 20 jobs | Total: 3638
Page 183 — 20 jobs | Total: 3658
Page 184 — 20 jobs | Total: 3678
Page 185 — 20 jobs | Total: 3698
Page 186 — 20 jobs | Total: 3718
Page 187 — 20 jobs | Total: 3738
Page 188 — 20 jobs | Total: 3758
Page 189 — 20 jobs | Total: 3778
Page 190 — 20 jobs | Total: 3798
Page 191 — 20 jobs | Total: 3818
Page 192 — 20 jobs | Total: 3838
Page 193 — 20 jobs | Total: 3858
Page 194 — 20 jobs | Total: 3878
Page 195 — 20 jobs | Total: 3898
Page 196 — 20 jobs | Total: 3918
Page 197 — 20 jobs | Total: 3938
Page 198 — 20 jobs | Total: 3958
Page 199 — 20 jobs | Total: 3978
Page 200 — 20 jobs | Total: 3998
Page 201 — 20 jobs | Total: 4018
Page 202 — 20 jobs | Total: 4038
Page 203 — 20 jobs | Total: 4058
Page 204 — 20 jobs | Total: 4078
Page 205 — 20 jobs | Total: 4098
Page 206 — 20 jobs | Total: 4118
Page 207 — 20 jobs | Total: 4138
Page 208 — 20 jobs | Total: 4158
Page 209 — 20 jobs | Total: 4178
Page 210 — 20 jobs | Total: 4198
Page 211 — 20 jobs | Total: 4218
Page 212 — 20 jobs | Total: 4238
Page 213 — 20 jobs | Total: 4258
Page 214 — 20 jobs | Total: 4278
Page 215 — 20 jobs | Total: 4298
Page 216 — 20 jobs | Total: 4318
Page 217 — 20 jobs | Total: 4338
Page 218 — 20 jobs | Total: 4358
Page 219 — 20 jobs | Total: 4378
Page 220 — 20 jobs | Total: 4398
Done. Total jobs: 4398

In [11]:
# list of dicts -> DataFrame — Day 1
df = pd.DataFrame(all_data)
print(df.shape)
df.head(10)

(4398, 9)

,Title,Company,Experience,Salary,Location,Rating,Reviews,Posted,Link
0,Data Analyst - (Immediate Joiners preferred),Capita,1-5 Yrs,Not Disclosed,"Hybrid - Pune, Mumbai (All Areas)",3.5,2694 Reviews,1 week ago,https://www.naukri.com/job-listings-data-analy...
1,Data Analyst,Capgemini,4-9 Yrs,Not Disclosed,"Hybrid - Chennai, Delhi / NCR, Mumbai (All Areas)",3.6,54214 Reviews,3 weeks ago,https://www.naukri.com/job-listings-data-analy...
2,Data Analyst,Snapdeal,1-6 Yrs,Not Disclosed,Gurugram,3.5,673 Reviews,3+ weeks ago,https://www.naukri.com/job-listings-data-analy...
3,Data Analyst,Kiya.ai,3-7 Yrs,5-11 Lacs PA,"Hybrid - Bengaluru, Mumbai (All Areas)",3.9,644 Reviews,3 days ago,https://www.naukri.com/job-listings-data-analy...
4,Data Analyst - Tableau/Looker/Salesforce (Remote),Indium Software,2-5 Yrs,12-16 Lacs PA,Remote,3.9,1372 Reviews,2 weeks ago,https://www.naukri.com/job-listings-data-analy...
5,Data Analyst,MNC,0-2 Yrs,2.75-5 Lacs PA,"Pimpri-Chinchwad, Pune",N/A,N/A,1 day ago,https://www.naukri.com/job-listings-data-analy...
6,Data Analyst,MNC,0-1 Yrs,2.5-5 Lacs PA,"Pimpri-Chinchwad, Pune",N/A,N/A,5 days ago,https://www.naukri.com/job-listings-data-analy...
7,Data Analyst,MNC,0-2 Yrs,2-5 Lacs PA,"Pimpri-Chinchwad, Pune",N/A,N/A,1 week ago,https://www.naukri.com/job-listings-data-analy...
8,Data Analyst,Codinglimits Nellore,0-1 Yrs,Not Disclosed,"Hyderabad, Chennai, Bengaluru",N/A,N/A,1 day ago,https://www.naukri.com/job-listings-data-analy...
9,Data Analyst,ti Steps,0-2 Yrs,3-4 Lacs PA,"Hyderabad, Chennai, Bengaluru",3.9,18 Reviews,1 day ago,https://www.naukri.com/job-listings-data-analy...

In [12]:
df

,Title,Company,Experience,Salary,Location,Rating,Reviews,Posted,Link
0,Data Analyst - (Immediate Joiners preferred),Capita,1-5 Yrs,Not Disclosed,"Hybrid - Pune, Mumbai (All Areas)",3.5,2694 Reviews,1 week ago,https://www.naukri.com/job-listings-data-analy...
1,Data Analyst,Capgemini,4-9 Yrs,Not Disclosed,"Hybrid - Chennai, Delhi / NCR, Mumbai (All Areas)",3.6,54214 Reviews,3 weeks ago,https://www.naukri.com/job-listings-data-analy...
2,Data Analyst,Snapdeal,1-6 Yrs,Not Disclosed,Gurugram,3.5,673 Reviews,3+ weeks ago,https://www.naukri.com/job-listings-data-analy...
3,Data Analyst,Kiya.ai,3-7 Yrs,5-11 Lacs PA,"Hybrid - Bengaluru, Mumbai (All Areas)",3.9,644 Reviews,3 days ago,https://www.naukri.com/job-listings-data-analy...
4,Data Analyst - Tableau/Looker/Salesforce (Remote),Indium Software,2-5 Yrs,12-16 Lacs PA,Remote,3.9,1372 Reviews,2 weeks ago,https://www.naukri.com/job-listings-data-analy...
...,...,...,...,...,...,...,...,...,...
4393,Sr. BI Analyst,Amherst Group,8-11 Yrs,Not Disclosed,"Kolkata, Mumbai, New Delhi, Hyderabad, Pune, C...",2.1,15 Reviews,3+ weeks ago,https://www.naukri.com/job-listings-sr-bi-anal...
4394,Senior AI Analyst,Impact Analytics,3-7 Yrs,Not Disclosed,Hybrid - Bengaluru,4.0,233 Reviews,3+ weeks ago,https://www.naukri.com/job-listings-senior-ai-...
4395,Scrum Master Senior Analyst,Cigna Medical Group,4-9 Yrs,Not Disclosed,Bengaluru,3.0,43 Reviews,3+ weeks ago,https://www.naukri.com/job-listings-scrum-mast...
4396,Sr. Operations Research Analyst,GForce Consulting Solutions,2-6 Yrs,Not Disclosed,"Kolkata, Mumbai, New Delhi, Hyderabad, Pune, C...",N/A,N/A,3+ weeks ago,https://www.naukri.com/job-listings-sr-operati...
4397,Advanced Analytics Senior Analyst,CBA Cross Border Associates,7-12 Yrs,Not Disclosed,Bengaluru,N/A,N/A,2 weeks ago,https://www.naukri.com/job-listings-advanced-a...

In [13]:
# Check how many N/A in each column
print("N/A counts per column:")
for col in df.columns:
    na_count = (df[col] == "N/A").sum()
    print(f"  {col}: {na_count} N/A out of {len(df)}")

N/A counts per column:
  Title: 0 N/A out of 4398
  Company: 0 N/A out of 4398
  Experience: 88 N/A out of 4398
  Salary: 0 N/A out of 4398
  Location: 16 N/A out of 4398
  Rating: 780 N/A out of 4398
  Reviews: 780 N/A out of 4398
  Posted: 0 N/A out of 4398
  Link: 0 N/A out of 4398

In [14]:
# df.to_csv — last BeautifulSoup concept
df.to_csv("naukri_jobs.csv", index=False)
print(f"Saved {len(df)} rows to naukri_jobs.csv")

Saved 4398 rows to naukri_jobs.csv

## If Rating / Reviews still show N/A

Run the cell below — it prints one card's HTML.  
Find the tag that holds rating and reviews, then update the selectors above.

In [ ]:
# Run this to inspect a card that HAS a rating
driver2 = get_driver()
driver2.get("https://www.naukri.com/data-analyst-jobs-in-all-india-1")
time.sleep(4)

html2 = driver2.page_source
soup2 = BeautifulSoup(html2, "html.parser")
cards2 = soup2.select("div.srp-jobtuple-wrapper")

# Find a card that has rating text
for card in cards2:
    text = card.get_text()
    if any(char.isdigit() for char in text[:200]):  # has some number (rating)
        print(card.prettify()[:2000])
        break

driver2.quit()