In [154]:
import pandas as pd
from bs4 import BeautifulSoup
import requests

In [155]:
url = "https://news.ycombinator.com/"

In [156]:
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36",
    "Accept-Language": "en-US,en;q=0.9",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
}

In [157]:
response = requests.get(url , headers = headers)

In [158]:
response.raise_for_status()

In [11]:
response.status_code

200

In [69]:
soup = BeautifulSoup(response.text , "html.parser")

In [16]:
# class="titleline"
item = soup.find("span", class_="titleline").find("a")

In [ ]:
title1 = item.text.strip()

In [23]:
rank = soup.find("span", class_="rank").text

In [24]:
rank

'1.'

In [59]:
titles_all = soup.find_all("span", class_="titleline")

In [60]:
for t in titles_all:
    item = t.find("a").text
    print(item)

MiMo-v2.5-Pro-UltraSpeed: 1T model with 1000 tokens per second
Show HN: Performative-UI – a react component library of design tropes
Zig by Example
Launch HN: Intuned (YC S22) – Build and run reliable browser automations as code
Anti-social: It's fads, not friends, which now dominate social media feeds
The Cypherpunk Library
How much of Thermo Fisher's antibody data has been manipulated?
Life is too short for a slow terminal
Zig Structs of Arrays (2024)
Dopamine Fracking
Italy's Bending Spoons, Owner of AOL and Vimeo, Files for Nasdaq IPO
1k Data Breaches Later, the Disclosure Lag Is Worse
A Farmer Donated Land to Turn into a Park. The City Is Building a Data Center
I replaced Spotify with a homemade FM radio station
Building from zero after addiction, prison, and a felony
Spherical Voronoi Diagram
Config Files That Run Code: Supply Chain Security Blindspot
APC–2 – A professional record cutter for producing original playback discs
The Smallest Brain You Can Build: A Perceptron in Python
A Family Project (2022)
Richard Scolyer Has Died
Playing with Vision Embeddings
SoulsOnly.tff – A font for humans not AI and keyboard firmware to type in it
Making peace with your unlived dreams (2023)
Nvidia partners with LG robotics to build humanoid robots in South Korea
New drug 'functionally cures' many hepatitis B virus infections
Amazon Cognito now supports multi-Region replication
Show HN: I Derived a Pancake
Tiny hackable CUDA language model implementation
A modular impact diverting mechanism for football helmets [pdf]

In [66]:
# class="athing submission"

In [76]:
# Testing
allcotent = soup.find_all("tr" , class_=["athing", "submission"])

In [77]:
allcontent

[<tr class="athing submission" id="48446639"><td align="right" class="title" valign="top"><span class="rank">1.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48446639&amp;how=up&amp;goto=news" id="up_48446639"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://mimo.xiaomi.com/blog/mimo-tilert-1000tps">MiMo-v2.5-Pro-UltraSpeed: 1T model with 1000 tokens per second</a><span class="sitebit comhead"> (<a href="from?site=xiaomi.com"><span class="sitestr">xiaomi.com</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48445554"><td align="right" class="title" valign="top"><span class="rank">2.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48445554&amp;how=up&amp;goto=news" id="up_48445554"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://vorpus.github.io/performativeUI/">Show HN: Performative-UI – a react component library of design tropes</a><span class="sitebit comhead"> (<a href="from?site=vorpus.github.io"><span class="sitestr">vorpus.github.io</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48444871"><td align="right" class="title" valign="top"><span class="rank">3.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48444871&amp;how=up&amp;goto=news" id="up_48444871"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://github.com/boringcollege/zig-by-example">Zig by Example</a><span class="sitebit comhead"> (<a href="from?site=github.com/boringcollege"><span class="sitestr">github.com/boringcollege</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48445171"><td align="right" class="title" valign="top"><span class="rank">4.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48445171&amp;how=up&amp;goto=news" id="up_48445171"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://intunedhq.com">Launch HN: Intuned (YC S22) – Build and run reliable browser automations as code</a><span class="sitebit comhead"> (<a href="from?site=intunedhq.com"><span class="sitestr">intunedhq.com</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48444228"><td align="right" class="title" valign="top"><span class="rank">5.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48444228&amp;how=up&amp;goto=news" id="up_48444228"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://www.bbc.com/worklife/article/20260520-how-social-media-ceased-to-be-social">Anti-social: It's fads, not friends, which now dominate social media feeds</a><span class="sitebit comhead"> (<a href="from?site=bbc.com"><span class="sitestr">bbc.com</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48442725"><td align="right" class="title" valign="top"><span class="rank">6.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48442725&amp;how=up&amp;goto=news" id="up_48442725"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://www.cypherpunkbooks.com">The Cypherpunk Library</a><span class="sitebit comhead"> (<a href="from?site=cypherpunkbooks.com"><span class="sitestr">cypherpunkbooks.com</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48442075"><td align="right" class="title" valign="top"><span class="rank">7.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48442075&amp;how=up&amp;goto=news" id="up_48442075"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://reeserichardson.blog/2026/05/28/how-much-of-thermo-fishers-antibody-data-has-been-manipulated/">How much of Thermo Fisher's antibody data has been manipulated?</a><span class="sitebit comhead"> (<a href="from?site=reeserichardson.blog"><span class="sitestr">reeserichardson.blog</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48424545"><td align="right" class="title" valign="top"><span class="rank">8.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48424545&amp;how=up&amp;goto=news" id="up_48424545"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://mijndertstuij.nl/posts/life-is-too-short-for-a-slow-terminal/">Life is too short for a slow terminal</a><span class="sitebit comhead"> (<a href="from?site=mijndertstuij.nl"><span class="sitestr">mijndertstuij.nl</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48394799"><td align="right" class="title" valign="top"><span class="rank">9.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48394799&amp;how=up&amp;goto=news" id="up_48394799"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://andreashohmann.com/zig-struct-of-arrays/">Zig Structs of Arrays (2024)</a><span class="sitebit comhead"> (<a href="from?site=andreashohmann.com"><span class="sitestr">andreashohmann.com</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48440792"><td align="right" class="title" valign="top"><span class="rank">10.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48440792&amp;how=up&amp;goto=news" id="up_48440792"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://igerman.cc/blog/dopamine-fracking/">Dopamine Fracking</a><span class="sitebit comhead"> (<a href="from?site=igerman.cc"><span class="sitestr">igerman.cc</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48446310"><td align="right" class="title" valign="top"><span class="rank">11.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48446310&amp;how=up&amp;goto=news" id="up_48446310"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://www.reuters.com/legal/transactional/italys-bending-spoons-files-us-ipo-2026-06-08/">Italy's Bending Spoons, Owner of AOL and Vimeo, Files for Nasdaq IPO</a><span class="sitebit comhead"> (<a href="from?site=reuters.com"><span class="sitestr">reuters.com</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48440952"><td align="right" class="title" valign="top"><span class="rank">12.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48440952&amp;how=up&amp;goto=news" id="up_48440952"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://www.troyhunt.com/1000-data-breaches-later-the-disclosure-lag-is-worse-than-ever/">1k Data Breaches Later, the Disclosure Lag Is Worse</a><span class="sitebit comhead"> (<a href="from?site=troyhunt.com"><span class="sitestr">troyhunt.com</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48446439"><td align="right" class="title" valign="top"><span class="rank">13.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48446439&amp;how=up&amp;goto=news" id="up_48446439"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://www.404media.co/a-farmer-donated-land-to-turn-into-a-park-the-city-is-building-a-massive-data-center-instead/">A Farmer Donated Land to Turn into a Park. The City Is Building a Data Center</a><span class="sitebit comhead"> (<a href="from?site=404media.co"><span class="sitestr">404media.co</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48446611"><td align="right" class="title" valign="top"><span class="rank">14.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48446611&amp;how=up&amp;goto=news" id="up_48446611"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://old.reddit.com/r/digitalminimalism/comments/1tes8yu/i_replaced_spotify_with_a_homemade_fm_radio/">I replaced Spotify with a homemade FM radio station</a><span class="sitebit comhead"> (<a href="from?site=reddit.com"><span class="sitestr">reddit.com</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48437406"><td align="right" class="title" valign="top"><span class="rank">15.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48437406&amp;how=up&amp;goto=news" id="up_48437406"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://gavinray97.github.io/blog/building-from-zero-after-addiction-prison-felony">Building from zero after addiction, prison, and a felony</a><span class="sitebit comhead"> (<a href="from?site=gavinray97.github.io"><span class="sitestr">gavinray97.github.io</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48385457"><td align="right" class="title" valign="top"><span class="rank">16.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48385457&amp;how=up&amp;goto=news" id="up_48385457"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://www.jasondavies.com/maps/voronoi/">Spherical Voronoi Diagram</a><span class="sitebit comhead"> (<a href="from?site=jasondavies.com"><span class="sitestr">jasondavies.com</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48443135"><td align="right" class="title" valign="top"><span class="rank">17.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48443135&amp;how=up&amp;goto=news" id="up_48443135"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://safedep.io/config-files-that-run-code/">Config Files That Run Code: Supply Chain Security Blindspot</a><span class="sitebit comhead"> (<a href="from?site=safedep.io"><span class="sitestr">safedep.io</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48440383"><td align="right" class="title" valign="top"><span class="rank">18.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48440383&amp;how=up&amp;goto=news" id="up_48440383"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://teenage.engineering/products/apc-2">APC–2 – A professional record cutter for producing original playback discs</a><span class="sitebit comhead"> (<a href="from?site=teenage.engineering"><span class="sitestr">teenage.engineering</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48440064"><td align="right" class="title" valign="top"><span class="rank">19.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48440064&amp;how=up&amp;goto=news" id="up_48440064"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://ranpara.net/posts/perceptron-explained-from-scratch/">The Smallest Brain You Can Build: A Perceptron in Python</a><span class="sitebit comhead"> (<a href="from?site=ranpara.net"><span class="sitestr">ranpara.net</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48413645"><td align="right" class="title" valign="top"><span class="rank">20.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48413645&amp;how=up&amp;goto=news" id="up_48413645"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://bittersoutherner.com/feature/2022/a-family-project">A Family Project (2022)</a><span class="sitebit comhead"> (<a href="from?site=bittersoutherner.com"><span class="sitestr">bittersoutherner.com</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48441242"><td align="right" class="title" valign="top"><span class="rank">21.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48441242&amp;how=up&amp;goto=news" id="up_48441242"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://www.bbc.com/news/articles/c14yz5jg476o">Richard Scolyer Has Died</a><span class="sitebit comhead"> (<a href="from?site=bbc.com"><span class="sitestr">bbc.com</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48413366"><td align="right" class="title" valign="top"><span class="rank">22.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48413366&amp;how=up&amp;goto=news" id="up_48413366"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://prestonbjensen.com/posts/playing-with-vision-embeddings">Playing with Vision Embeddings</a><span class="sitebit comhead"> (<a href="from?site=prestonbjensen.com"><span class="sitestr">prestonbjensen.com</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48445469"><td align="right" class="title" valign="top"><span class="rank">23.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48445469&amp;how=up&amp;goto=news" id="up_48445469"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://github.com/convictional/souls-only" rel="nofollow">SoulsOnly.tff – A font for humans not AI and keyboard firmware to type in it</a><span class="sitebit comhead"> (<a href="from?site=github.com/convictional"><span class="sitestr">github.com/convictional</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48437290"><td align="right" class="title" valign="top"><span class="rank">24.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48437290&amp;how=up&amp;goto=news" id="up_48437290"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://nik.art/making-peace-with-your-unlived-dreams/">Making peace with your unlived dreams (2023)</a><span class="sitebit comhead"> (<a href="from?site=nik.art"><span class="sitestr">nik.art</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48444451"><td align="right" class="title" valign="top"><span class="rank">25.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48444451&amp;how=up&amp;goto=news" id="up_48444451"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://blogs.nvidia.com/blog/nvidia-and-lg-group-ai-factory/">Nvidia partners with LG robotics to build humanoid robots in South Korea</a><span class="sitebit comhead"> (<a href="from?site=nvidia.com"><span class="sitestr">nvidia.com</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48440463"><td align="right" class="title" valign="top"><span class="rank">26.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48440463&amp;how=up&amp;goto=news" id="up_48440463"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://www.science.org/content/article/new-drug-functionally-cures-many-hepatitis-b-virus-infections?user_id=66c4bf745d78644b3aa57b08">New drug 'functionally cures' many hepatitis B virus infections</a><span class="sitebit comhead"> (<a href="from?site=science.org"><span class="sitestr">science.org</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48446521"><td align="right" class="title" valign="top"><span class="rank">27.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48446521&amp;how=up&amp;goto=news" id="up_48446521"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://aws.amazon.com/about-aws/whats-new/2026/06/amazon-cognito-multi-region/" rel="nofollow">Amazon Cognito now supports multi-Region replication</a><span class="sitebit comhead"> (<a href="from?site=amazon.com"><span class="sitestr">amazon.com</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48408854"><td align="right" class="title" valign="top"><span class="rank">28.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48408854&amp;how=up&amp;goto=news" id="up_48408854"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://www.absurdlyoptimized.com/recipes/pancakes/">Show HN: I Derived a Pancake</a><span class="sitebit comhead"> (<a href="from?site=absurdlyoptimized.com"><span class="sitestr">absurdlyoptimized.com</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48415828"><td align="right" class="title" valign="top"><span class="rank">29.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48415828&amp;how=up&amp;goto=news" id="up_48415828"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://github.com/markusheimerl/gpt">Tiny hackable CUDA language model implementation</a><span class="sitebit comhead"> (<a href="from?site=github.com/markusheimerl"><span class="sitestr">github.com/markusheimerl</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48430608"><td align="right" class="title" valign="top"><span class="rank">30.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48430608&amp;how=up&amp;goto=news" id="up_48430608"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://www.sfu.ca/~gwa5/pdf/2020_04.pdf">A modular impact diverting mechanism for football helmets [pdf]</a><span class="sitebit comhead"> (<a href="from?site=sfu.ca"><span class="sitestr">sfu.ca</span></a>)</span></span></td></tr>]

In [74]:
allcontent = soup.select("tr.athing.submission")

In [75]:
allcontent

[<tr class="athing submission" id="48446639"><td align="right" class="title" valign="top"><span class="rank">1.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48446639&amp;how=up&amp;goto=news" id="up_48446639"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://mimo.xiaomi.com/blog/mimo-tilert-1000tps">MiMo-v2.5-Pro-UltraSpeed: 1T model with 1000 tokens per second</a><span class="sitebit comhead"> (<a href="from?site=xiaomi.com"><span class="sitestr">xiaomi.com</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48445554"><td align="right" class="title" valign="top"><span class="rank">2.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48445554&amp;how=up&amp;goto=news" id="up_48445554"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://vorpus.github.io/performativeUI/">Show HN: Performative-UI – a react component library of design tropes</a><span class="sitebit comhead"> (<a href="from?site=vorpus.github.io"><span class="sitestr">vorpus.github.io</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48444871"><td align="right" class="title" valign="top"><span class="rank">3.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48444871&amp;how=up&amp;goto=news" id="up_48444871"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://github.com/boringcollege/zig-by-example">Zig by Example</a><span class="sitebit comhead"> (<a href="from?site=github.com/boringcollege"><span class="sitestr">github.com/boringcollege</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48445171"><td align="right" class="title" valign="top"><span class="rank">4.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48445171&amp;how=up&amp;goto=news" id="up_48445171"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://intunedhq.com">Launch HN: Intuned (YC S22) – Build and run reliable browser automations as code</a><span class="sitebit comhead"> (<a href="from?site=intunedhq.com"><span class="sitestr">intunedhq.com</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48444228"><td align="right" class="title" valign="top"><span class="rank">5.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48444228&amp;how=up&amp;goto=news" id="up_48444228"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://www.bbc.com/worklife/article/20260520-how-social-media-ceased-to-be-social">Anti-social: It's fads, not friends, which now dominate social media feeds</a><span class="sitebit comhead"> (<a href="from?site=bbc.com"><span class="sitestr">bbc.com</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48442725"><td align="right" class="title" valign="top"><span class="rank">6.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48442725&amp;how=up&amp;goto=news" id="up_48442725"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://www.cypherpunkbooks.com">The Cypherpunk Library</a><span class="sitebit comhead"> (<a href="from?site=cypherpunkbooks.com"><span class="sitestr">cypherpunkbooks.com</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48442075"><td align="right" class="title" valign="top"><span class="rank">7.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48442075&amp;how=up&amp;goto=news" id="up_48442075"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://reeserichardson.blog/2026/05/28/how-much-of-thermo-fishers-antibody-data-has-been-manipulated/">How much of Thermo Fisher's antibody data has been manipulated?</a><span class="sitebit comhead"> (<a href="from?site=reeserichardson.blog"><span class="sitestr">reeserichardson.blog</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48424545"><td align="right" class="title" valign="top"><span class="rank">8.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48424545&amp;how=up&amp;goto=news" id="up_48424545"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://mijndertstuij.nl/posts/life-is-too-short-for-a-slow-terminal/">Life is too short for a slow terminal</a><span class="sitebit comhead"> (<a href="from?site=mijndertstuij.nl"><span class="sitestr">mijndertstuij.nl</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48394799"><td align="right" class="title" valign="top"><span class="rank">9.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48394799&amp;how=up&amp;goto=news" id="up_48394799"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://andreashohmann.com/zig-struct-of-arrays/">Zig Structs of Arrays (2024)</a><span class="sitebit comhead"> (<a href="from?site=andreashohmann.com"><span class="sitestr">andreashohmann.com</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48440792"><td align="right" class="title" valign="top"><span class="rank">10.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48440792&amp;how=up&amp;goto=news" id="up_48440792"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://igerman.cc/blog/dopamine-fracking/">Dopamine Fracking</a><span class="sitebit comhead"> (<a href="from?site=igerman.cc"><span class="sitestr">igerman.cc</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48446310"><td align="right" class="title" valign="top"><span class="rank">11.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48446310&amp;how=up&amp;goto=news" id="up_48446310"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://www.reuters.com/legal/transactional/italys-bending-spoons-files-us-ipo-2026-06-08/">Italy's Bending Spoons, Owner of AOL and Vimeo, Files for Nasdaq IPO</a><span class="sitebit comhead"> (<a href="from?site=reuters.com"><span class="sitestr">reuters.com</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48440952"><td align="right" class="title" valign="top"><span class="rank">12.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48440952&amp;how=up&amp;goto=news" id="up_48440952"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://www.troyhunt.com/1000-data-breaches-later-the-disclosure-lag-is-worse-than-ever/">1k Data Breaches Later, the Disclosure Lag Is Worse</a><span class="sitebit comhead"> (<a href="from?site=troyhunt.com"><span class="sitestr">troyhunt.com</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48446439"><td align="right" class="title" valign="top"><span class="rank">13.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48446439&amp;how=up&amp;goto=news" id="up_48446439"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://www.404media.co/a-farmer-donated-land-to-turn-into-a-park-the-city-is-building-a-massive-data-center-instead/">A Farmer Donated Land to Turn into a Park. The City Is Building a Data Center</a><span class="sitebit comhead"> (<a href="from?site=404media.co"><span class="sitestr">404media.co</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48446611"><td align="right" class="title" valign="top"><span class="rank">14.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48446611&amp;how=up&amp;goto=news" id="up_48446611"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://old.reddit.com/r/digitalminimalism/comments/1tes8yu/i_replaced_spotify_with_a_homemade_fm_radio/">I replaced Spotify with a homemade FM radio station</a><span class="sitebit comhead"> (<a href="from?site=reddit.com"><span class="sitestr">reddit.com</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48437406"><td align="right" class="title" valign="top"><span class="rank">15.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48437406&amp;how=up&amp;goto=news" id="up_48437406"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://gavinray97.github.io/blog/building-from-zero-after-addiction-prison-felony">Building from zero after addiction, prison, and a felony</a><span class="sitebit comhead"> (<a href="from?site=gavinray97.github.io"><span class="sitestr">gavinray97.github.io</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48385457"><td align="right" class="title" valign="top"><span class="rank">16.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48385457&amp;how=up&amp;goto=news" id="up_48385457"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://www.jasondavies.com/maps/voronoi/">Spherical Voronoi Diagram</a><span class="sitebit comhead"> (<a href="from?site=jasondavies.com"><span class="sitestr">jasondavies.com</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48443135"><td align="right" class="title" valign="top"><span class="rank">17.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48443135&amp;how=up&amp;goto=news" id="up_48443135"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://safedep.io/config-files-that-run-code/">Config Files That Run Code: Supply Chain Security Blindspot</a><span class="sitebit comhead"> (<a href="from?site=safedep.io"><span class="sitestr">safedep.io</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48440383"><td align="right" class="title" valign="top"><span class="rank">18.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48440383&amp;how=up&amp;goto=news" id="up_48440383"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://teenage.engineering/products/apc-2">APC–2 – A professional record cutter for producing original playback discs</a><span class="sitebit comhead"> (<a href="from?site=teenage.engineering"><span class="sitestr">teenage.engineering</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48440064"><td align="right" class="title" valign="top"><span class="rank">19.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48440064&amp;how=up&amp;goto=news" id="up_48440064"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://ranpara.net/posts/perceptron-explained-from-scratch/">The Smallest Brain You Can Build: A Perceptron in Python</a><span class="sitebit comhead"> (<a href="from?site=ranpara.net"><span class="sitestr">ranpara.net</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48413645"><td align="right" class="title" valign="top"><span class="rank">20.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48413645&amp;how=up&amp;goto=news" id="up_48413645"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://bittersoutherner.com/feature/2022/a-family-project">A Family Project (2022)</a><span class="sitebit comhead"> (<a href="from?site=bittersoutherner.com"><span class="sitestr">bittersoutherner.com</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48441242"><td align="right" class="title" valign="top"><span class="rank">21.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48441242&amp;how=up&amp;goto=news" id="up_48441242"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://www.bbc.com/news/articles/c14yz5jg476o">Richard Scolyer Has Died</a><span class="sitebit comhead"> (<a href="from?site=bbc.com"><span class="sitestr">bbc.com</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48413366"><td align="right" class="title" valign="top"><span class="rank">22.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48413366&amp;how=up&amp;goto=news" id="up_48413366"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://prestonbjensen.com/posts/playing-with-vision-embeddings">Playing with Vision Embeddings</a><span class="sitebit comhead"> (<a href="from?site=prestonbjensen.com"><span class="sitestr">prestonbjensen.com</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48445469"><td align="right" class="title" valign="top"><span class="rank">23.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48445469&amp;how=up&amp;goto=news" id="up_48445469"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://github.com/convictional/souls-only" rel="nofollow">SoulsOnly.tff – A font for humans not AI and keyboard firmware to type in it</a><span class="sitebit comhead"> (<a href="from?site=github.com/convictional"><span class="sitestr">github.com/convictional</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48437290"><td align="right" class="title" valign="top"><span class="rank">24.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48437290&amp;how=up&amp;goto=news" id="up_48437290"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://nik.art/making-peace-with-your-unlived-dreams/">Making peace with your unlived dreams (2023)</a><span class="sitebit comhead"> (<a href="from?site=nik.art"><span class="sitestr">nik.art</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48444451"><td align="right" class="title" valign="top"><span class="rank">25.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48444451&amp;how=up&amp;goto=news" id="up_48444451"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://blogs.nvidia.com/blog/nvidia-and-lg-group-ai-factory/">Nvidia partners with LG robotics to build humanoid robots in South Korea</a><span class="sitebit comhead"> (<a href="from?site=nvidia.com"><span class="sitestr">nvidia.com</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48440463"><td align="right" class="title" valign="top"><span class="rank">26.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48440463&amp;how=up&amp;goto=news" id="up_48440463"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://www.science.org/content/article/new-drug-functionally-cures-many-hepatitis-b-virus-infections?user_id=66c4bf745d78644b3aa57b08">New drug 'functionally cures' many hepatitis B virus infections</a><span class="sitebit comhead"> (<a href="from?site=science.org"><span class="sitestr">science.org</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48446521"><td align="right" class="title" valign="top"><span class="rank">27.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48446521&amp;how=up&amp;goto=news" id="up_48446521"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://aws.amazon.com/about-aws/whats-new/2026/06/amazon-cognito-multi-region/" rel="nofollow">Amazon Cognito now supports multi-Region replication</a><span class="sitebit comhead"> (<a href="from?site=amazon.com"><span class="sitestr">amazon.com</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48408854"><td align="right" class="title" valign="top"><span class="rank">28.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48408854&amp;how=up&amp;goto=news" id="up_48408854"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://www.absurdlyoptimized.com/recipes/pancakes/">Show HN: I Derived a Pancake</a><span class="sitebit comhead"> (<a href="from?site=absurdlyoptimized.com"><span class="sitestr">absurdlyoptimized.com</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48415828"><td align="right" class="title" valign="top"><span class="rank">29.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48415828&amp;how=up&amp;goto=news" id="up_48415828"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://github.com/markusheimerl/gpt">Tiny hackable CUDA language model implementation</a><span class="sitebit comhead"> (<a href="from?site=github.com/markusheimerl"><span class="sitestr">github.com/markusheimerl</span></a>)</span></span></td></tr>,
 <tr class="athing submission" id="48430608"><td align="right" class="title" valign="top"><span class="rank">30.</span></td><td class="votelinks" valign="top"><center><a href="vote?id=48430608&amp;how=up&amp;goto=news" id="up_48430608"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://www.sfu.ca/~gwa5/pdf/2020_04.pdf">A modular impact diverting mechanism for football helmets [pdf]</a><span class="sitebit comhead"> (<a href="from?site=sfu.ca"><span class="sitestr">sfu.ca</span></a>)</span></span></td></tr>]

In [97]:
l = []
for item in allcontent:
    rank = item.find("span" , class_='rank').text
    title = item.find("span" , class_='titleline').find("a").text
    url = item.find("span" , class_='sitestr').text
    
    dic = { 
        "Rank" : rank,
        "Title" : title,
        "URL" : url
    }
    l.append(dic)

In [104]:
df1 = pd.DataFrame(l)
df1

,Rank,Title,URL
0,1.,MiMo-v2.5-Pro-UltraSpeed: 1T model with 1000 t...,xiaomi.com
1,2.,Show HN: Performative-UI – a react component l...,vorpus.github.io
2,3.,Zig by Example,github.com/boringcollege
3,4.,Launch HN: Intuned (YC S22) – Build and run re...,intunedhq.com
4,5.,"Anti-social: It's fads, not friends, which now...",bbc.com
5,6.,The Cypherpunk Library,cypherpunkbooks.com
6,7.,How much of Thermo Fisher's antibody data has ...,reeserichardson.blog
7,8.,Life is too short for a slow terminal,mijndertstuij.nl
8,9.,Zig Structs of Arrays (2024),andreashohmann.com
9,10.,Dopamine Fracking,igerman.cc
10,11.,"Italy's Bending Spoons, Owner of AOL and Vimeo...",reuters.com
11,12.,"1k Data Breaches Later, the Disclosure Lag Is ...",troyhunt.com
12,13.,A Farmer Donated Land to Turn into a Park. The...,404media.co
13,14.,I replaced Spotify with a homemade FM radio st...,reddit.com
14,15.,"Building from zero after addiction, prison, an...",gavinray97.github.io
15,16.,Spherical Voronoi Diagram,jasondavies.com
16,17.,Config Files That Run Code: Supply Chain Secur...,safedep.io
17,18.,APC–2 – A professional record cutter for produ...,teenage.engineering
18,19.,The Smallest Brain You Can Build: A Perceptron...,ranpara.net
19,20.,A Family Project (2022),bittersoutherner.com
20,21.,Richard Scolyer Has Died,bbc.com
21,22.,Playing with Vision Embeddings,prestonbjensen.com
22,23.,SoulsOnly.tff – A font for humans not AI and k...,github.com/convictional
23,24.,Making peace with your unlived dreams (2023),nik.art
24,25.,Nvidia partners with LG robotics to build huma...,nvidia.com
25,26.,New drug 'functionally cures' many hepatitis B...,science.org
26,27.,Amazon Cognito now supports multi-Region repli...,amazon.com
27,28.,Show HN: I Derived a Pancake,absurdlyoptimized.com
28,29.,Tiny hackable CUDA language model implementation,github.com/markusheimerl
29,30.,A modular impact diverting mechanism for footb...,sfu.ca

In [84]:
allother = soup.find_all("span",class_='subline')

In [100]:
m = []
for item in allother:
    points = item.find("span").text
    author = item.find("a").text
    comments = item.find_all("a")[-1].text

    dic = {
        "Points" : points,
        "Author" : author,
        "Comments" : comments
    }

    m.append(dic)

In [102]:
df2 = pd.DataFrame(m)
df2

        Points           Author      Comments
0    60 points       gainsurier   10 comments
1   213 points          lizhang   42 comments
2   145 points          dariubs   67 comments
3    65 points         fkilaiwi   15 comments
4   242 points    1vuio0pswjnm7  212 comments
5   234 points         yu3zhou4   76 comments
6   259 points           mhrmsn   56 comments
7    36 points       emschwartz   31 comments
8    84 points            Tomte   19 comments
9   609 points             igmn  307 comments
10   32 points          mmarian   13 comments
11  255 points  882542F3884314B  100 comments
12   25 points           greedo     1 comment
13   22 points      dredmorbius   10 comments
14  799 points         gavinray  364 comments
15   89 points    marysminefnuf   23 comments
16   48 points          signa11   10 comments
17  251 points       vthommeret  159 comments
18  272 points   DevarshRanpara   60 comments
19   68 points     surprisetalk    5 comments
20  112 points        nicwilson   30 comments
21  123 points          prestoj   10 comments
22   15 points      billtarbell    9 comments
23  281 points         herbertl  175 comments
24   52 points            spwa4   47 comments
25  247 points            gmays   43 comments
26   12 points          mooreds    3 comments
27  302 points           bkazez  120 comments
28   60 points    markusheimerl   13 comments
29   14 points              luu    6 comments

In [107]:
df = pd.concat([df1,df2] , axis = 1)
df

,Rank,Title,URL,Points,Author,Comments
0,1.,MiMo-v2.5-Pro-UltraSpeed: 1T model with 1000 t...,xiaomi.com,60 points,gainsurier,10 comments
1,2.,Show HN: Performative-UI – a react component l...,vorpus.github.io,213 points,lizhang,42 comments
2,3.,Zig by Example,github.com/boringcollege,145 points,dariubs,67 comments
3,4.,Launch HN: Intuned (YC S22) – Build and run re...,intunedhq.com,65 points,fkilaiwi,15 comments
4,5.,"Anti-social: It's fads, not friends, which now...",bbc.com,242 points,1vuio0pswjnm7,212 comments
5,6.,The Cypherpunk Library,cypherpunkbooks.com,234 points,yu3zhou4,76 comments
6,7.,How much of Thermo Fisher's antibody data has ...,reeserichardson.blog,259 points,mhrmsn,56 comments
7,8.,Life is too short for a slow terminal,mijndertstuij.nl,36 points,emschwartz,31 comments
8,9.,Zig Structs of Arrays (2024),andreashohmann.com,84 points,Tomte,19 comments
9,10.,Dopamine Fracking,igerman.cc,609 points,igmn,307 comments
10,11.,"Italy's Bending Spoons, Owner of AOL and Vimeo...",reuters.com,32 points,mmarian,13 comments
11,12.,"1k Data Breaches Later, the Disclosure Lag Is ...",troyhunt.com,255 points,882542F3884314B,100 comments
12,13.,A Farmer Donated Land to Turn into a Park. The...,404media.co,25 points,greedo,1 comment
13,14.,I replaced Spotify with a homemade FM radio st...,reddit.com,22 points,dredmorbius,10 comments
14,15.,"Building from zero after addiction, prison, an...",gavinray97.github.io,799 points,gavinray,364 comments
15,16.,Spherical Voronoi Diagram,jasondavies.com,89 points,marysminefnuf,23 comments
16,17.,Config Files That Run Code: Supply Chain Secur...,safedep.io,48 points,signa11,10 comments
17,18.,APC–2 – A professional record cutter for produ...,teenage.engineering,251 points,vthommeret,159 comments
18,19.,The Smallest Brain You Can Build: A Perceptron...,ranpara.net,272 points,DevarshRanpara,60 comments
19,20.,A Family Project (2022),bittersoutherner.com,68 points,surprisetalk,5 comments
20,21.,Richard Scolyer Has Died,bbc.com,112 points,nicwilson,30 comments
21,22.,Playing with Vision Embeddings,prestonbjensen.com,123 points,prestoj,10 comments
22,23.,SoulsOnly.tff – A font for humans not AI and k...,github.com/convictional,15 points,billtarbell,9 comments
23,24.,Making peace with your unlived dreams (2023),nik.art,281 points,herbertl,175 comments
24,25.,Nvidia partners with LG robotics to build huma...,nvidia.com,52 points,spwa4,47 comments
25,26.,New drug 'functionally cures' many hepatitis B...,science.org,247 points,gmays,43 comments
26,27.,Amazon Cognito now supports multi-Region repli...,amazon.com,12 points,mooreds,3 comments
27,28.,Show HN: I Derived a Pancake,absurdlyoptimized.com,302 points,bkazez,120 comments
28,29.,Tiny hackable CUDA language model implementation,github.com/markusheimerl,60 points,markusheimerl,13 comments
29,30.,A modular impact diverting mechanism for footb...,sfu.ca,14 points,luu,6 comments

In [110]:
df['Rank'] = df['Rank'].str.replace('.' , '')

In [116]:
df['Points'] = df['Points'].str[:-6]

In [120]:
df['Comments'] = df['Comments'].str[:-8].str.strip()

In [121]:
df

,Rank,Title,URL,Points,Author,Comments
0,1,MiMo-v2.5-Pro-UltraSpeed: 1T model with 1000 t...,xiaomi.com,60,gainsurier,10
1,2,Show HN: Performative-UI – a react component l...,vorpus.github.io,213,lizhang,42
2,3,Zig by Example,github.com/boringcollege,145,dariubs,67
3,4,Launch HN: Intuned (YC S22) – Build and run re...,intunedhq.com,65,fkilaiwi,15
4,5,"Anti-social: It's fads, not friends, which now...",bbc.com,242,1vuio0pswjnm7,212
5,6,The Cypherpunk Library,cypherpunkbooks.com,234,yu3zhou4,76
6,7,How much of Thermo Fisher's antibody data has ...,reeserichardson.blog,259,mhrmsn,56
7,8,Life is too short for a slow terminal,mijndertstuij.nl,36,emschwartz,31
8,9,Zig Structs of Arrays (2024),andreashohmann.com,84,Tomte,19
9,10,Dopamine Fracking,igerman.cc,609,igmn,307
10,11,"Italy's Bending Spoons, Owner of AOL and Vimeo...",reuters.com,32,mmarian,13
11,12,"1k Data Breaches Later, the Disclosure Lag Is ...",troyhunt.com,255,882542F3884314B,100
12,13,A Farmer Donated Land to Turn into a Park. The...,404media.co,25,greedo,1
13,14,I replaced Spotify with a homemade FM radio st...,reddit.com,22,dredmorbius,10
14,15,"Building from zero after addiction, prison, an...",gavinray97.github.io,799,gavinray,364
15,16,Spherical Voronoi Diagram,jasondavies.com,89,marysminefnuf,23
16,17,Config Files That Run Code: Supply Chain Secur...,safedep.io,48,signa11,10
17,18,APC–2 – A professional record cutter for produ...,teenage.engineering,251,vthommeret,159
18,19,The Smallest Brain You Can Build: A Perceptron...,ranpara.net,272,DevarshRanpara,60
19,20,A Family Project (2022),bittersoutherner.com,68,surprisetalk,5
20,21,Richard Scolyer Has Died,bbc.com,112,nicwilson,30
21,22,Playing with Vision Embeddings,prestonbjensen.com,123,prestoj,10
22,23,SoulsOnly.tff – A font for humans not AI and k...,github.com/convictional,15,billtarbell,9
23,24,Making peace with your unlived dreams (2023),nik.art,281,herbertl,175
24,25,Nvidia partners with LG robotics to build huma...,nvidia.com,52,spwa4,47
25,26,New drug 'functionally cures' many hepatitis B...,science.org,247,gmays,43
26,27,Amazon Cognito now supports multi-Region repli...,amazon.com,12,mooreds,3
27,28,Show HN: I Derived a Pancake,absurdlyoptimized.com,302,bkazez,120
28,29,Tiny hackable CUDA language model implementation,github.com/markusheimerl,60,markusheimerl,13
29,30,A modular impact diverting mechanism for footb...,sfu.ca,14,luu,6

In [125]:
df['Points'] = df['Points'].str.strip()

In [132]:
df[df['Points'] == '89']['Author'].values.item()

'marysminefnuf'

In [135]:
df['Comments'] = df['Comments'].str.strip()

In [137]:
df['Comments'] = df['Comments'].astype('int')

In [139]:
df['Comments'].mean().item()

67.86666666666666

In [143]:
df['Points'] = df['Points'].astype('int')

In [151]:
df.sort_values('Points',ascending = False).head()['Title'].values[:]

array(['Building from zero after addiction, prison, and a felony',
       'Dopamine Fracking', 'Show HN: I Derived a Pancake',
       'Making peace with your unlived dreams (2023)',
       'The Smallest Brain You Can Build: A Perceptron in Python'],
      dtype=object)